### ISSUE TITLE
change direction of items

### ISSUE THREAD

**Issue by faezesaghafi** [google/flexbox-layout#106]
hi. your lib is awesome, so I want to use it in my app. the problem is I want to change direction of items be right to left. can u help me?

**Comment by faezesaghafi** [comment]
app:justifyContent="flex_end"

**Comment by thagikura** [comment]
Hi thanks for your interest.

Is your requirement met by setting `app:flexDirection="row_reverse"`?

**Comment by faezesaghafi** [comment]
thanke you, it works

**Comment by thagikura** [comment]
Ok thanks.
