### ISSUE TITLE
Add `android:foreground` attribute support

### ISSUE THREAD

**Issue by stepango** [google/flexbox-layout#109]
For now, there is no way to add foreground on Flexbox-layout

**Comment by thagikura** [comment]
Thanks for your suggestion, however a foreground image can be achieved in some alternate ways like explained in this StackOverflow [thread](http://stackoverflow.com/questions/16787738/how-to-set-foreground-attribute-to-other-non-framelayout-view).

So I feel adding the foreground support is not so useful for the developers using the FlexboxLayout. I'm closing this for now,  please re-open it if you insist.
