### ISSUE TITLE
Float value is not accepted as Flex Grow on the sample application

### ISSUE THREAD

**Issue by hkurokawa** [google/flexbox-layout#112]
# Description
On the sample application, I changed **Flex Grow** for the last item from `0.0` to `1.0`. I expected it made the item expand to the end of the line. However, the width of the item didn't change and when I opened the dialog again, **Flex Grow** was `0.0`.

# Environment
- Mac OS X 10.11.5
- Android Emulator, Nexus One, API 17
- Android Studio 2.2 Beta 3

# Steps
1. Open the sample app
2. Click the item **3**
3. Change the value of **Flex Grow** from `0.0` to `1.0`
4. Click OK on the dialog

# Result
Nothing happens

# Expected Result
The item **3** expands to the end of the line

# Remarks
I found the below code and it seems the code failed to parse a text containing dots `.` as an integer, such as `1.0`. In fact, when I input `1` instead of `1.0` at step 3, the result was as expected.

https://github.com/google/flexbox-layout/blob/master/app/src/main/java/com/google/android/apps/flexbox/FlexItemEditFragment.java#L376

I am wondering you might have to update your `FlexEditTextWatcher` so that it can accept a flow value as an input when the ID of the TextInputLayout is `input_layout_flex_grow` or `input_layout_flex_shrink`. I'm creating a small patch to fix it to clarify the point and will let you know when it's ready.

Thank you.

**Comment by thagikura** [comment]
Wow, thanks for the detailed description and even a PR! Really appreciate it.
Let me check your PR.

Thanks!

**Comment by thagikura** [comment]
Fixed by #113. 
Thanks again!
