### ISSUE TITLE
The demo app has a problem of the dialog theme with Kitkat devices

### ISSUE THREAD

**Issue by androhi** [google/flexbox-layout#115]
This demo app is so amazing!
But I thought the theme was not good when I open the dialog with KitKat device.

This is the screen I saw.

![device-2016-09-02-145520](https://cloud.githubusercontent.com/assets/1404787/18201131/4ee85d56-7143-11e6-8f0b-5d0ef571b1a8.png)
*Sony Xperia Z1f Android 4.4.2*

I guess it needs the theme of `android.R.style.Theme_Holo_Light_Dialog` on between Honeycomb and Kitkat.

**Comment by thagikura** [comment]
Oops. Thanks for the report! Sorry for the inconvenience... I'll fix it.
