### ISSUE TITLE
Invalid sizing of child when it has no size but only flexGrow

### ISSUE THREAD

**Issue by andrey-shikhov** [google/flexbox-layout#139]
Android snippet:
https://gist.github.com/andrey-shikhov/6f65ca14bf3d44f0393a0f8ba6b9b764

![screenshot_1479233115](https://cloud.githubusercontent.com/assets/340643/20317692/cb04939e-ab6f-11e6-91a3-88c6e85ff7e6.png)

Css snippet:
https://gist.github.com/andrey-shikhov/78d24b0724b1cc5f5690c2aa3597ddab

![css-screen](https://cloud.githubusercontent.com/assets/340643/20317738/f6ad6070-ab6f-11e6-9416-8488fa4d458d.png)

A Very weird behavior of children measuring when a child has only flexGrow value without width. In this example, android flexbox gives height to child equal to count of chars int text(child of child in flexbox).
It really different from css flexbox(css snippet above)

**Comment by thagikura** [comment]
Thanks for the report.

It looks like the height of the text views are calculated with its width set to 0 at first, so the height of those are expanded as the text length is increased.

Anyway I'll fix this.

Thanks!

**Comment by thagikura** [comment]
Fixed by #140. I'll release the new version of the library shortly (with other bug fixes).
