### ISSUE TITLE
Element margins do not expand flexbox container with wrap_content

### ISSUE THREAD

**Issue by jjaksic** [google/flexbox-layout#154]
Version 0.2.4 introduced a layout bug, I believe it was [this commit](https://github.com/google/flexbox-layout/pull/140/commits/e2884eddb24a1c5ca07d1b6552a639f0510a38ea).

A FlexboxLayout with height="wrap_content" is supposed to set its height to fit all contained elements. This does not work correctly when elements have a margin. The container height only matches the height of the element itself, **without** the margin, but then the element gets shrunk so that it fits into the container **with** the margin. This results in a part of the element being cut off by the margin, like in the following example:

![image](https://cloud.githubusercontent.com/assets/881721/20942506/74d2d052-bbb0-11e6-82ee-1a5a8c74e2b4.png)

The above label has a marginBottom of 6dp and it's cut off at the bottom by 6dp. The glitch goes away if we remove the margin (which it not desirable), or if we revert to 0.2.3.

Layout code for the above example (simplified):
```
    <com.google.android.flexbox.FlexboxLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:flexWrap="wrap"
        app:justifyContent="flex_end">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginBottom="6dp"
            android:layout_gravity="top"
            android:layout_weight="1"
            app:layout_flexBasisPercent="50%"
            app:layout_flexGrow="1"
            app:layout_flexShrink="0"/>
```

**Comment by thagikura** [comment]
Sorry about that, thanks for filing it. I'll take a look.
