### ISSUE TITLE
Add `maxline` attribute support

### ISSUE THREAD

**Issue by Letty-Liang** [google/flexbox-layout#156]
hope to be added in order to limit the maxLines

**Comment by thagikura** [comment]
Thanks for the suggestion, but I don't come up with an use case where the maxLines attribute is useful. Like what use case do you expect that attribute?

**Comment by SouhaibGuitouni** [comment]
First issue I had when I tried FlexBoxLayout. It would be helpful if we had this attribute. In my case I have a FlexBoxLayout on top of a RecyclerView. The FlexBoxLayout shows the names of the selected elements in the list. In my case I don't want it to be more than two lines (otherwise the FlexBox would cover the screen if I select many elements), I would show a label "+N" for the rest of the selected items.

**Comment by osipovaleks** [comment]
what about this functionality?

**Comment by Bringoff** [comment]
So, no progress with this?

**Comment by YuriDenison** [comment]
It would be useful in my case too. 
Could you please provide any ETA for this issue?

**Comment by yifleo** [comment]
Same problem, i only need one line in header of RecyclerView

**Comment by thagikura** [comment]
I wanted to be careful for adding a feature that the original Flexbox doesn't have, but it looks like this is going to be useful for a lot of developers.
I'll add this feature on my TODO list.

**Comment by chinahope** [comment]
Same problem, not only and   
add enqueue child view to pop old child view also limit flexboxlayout max lines

**Comment by Coehill** [comment]
Also looking for this feature.  I noticed that this issue is closed but it references another issue which is also closed and referenced this issue.  Maybe you should leave this one open since it hasn't been implemented yet.

**Comment by syzhugh** [comment]
can FlexboxLayoutManager specify the maximum number of lines?

**Comment by oyty** [comment]
manager.setMaxLine(1) is useless for FlexboxLayoutManager.

`private static class OnViewGlobalLayoutListener implements ViewTreeObserver.OnGlobalLayoutListener {
    private final static int maxHeight = 130;
    private View view;

    public OnViewGlobalLayoutListener(View view) {
        this.view = view;
    }

    @Override
    public void onGlobalLayout() {
        if (view.getHeight() > maxHeight)
            view.getLayoutParams().height = maxHeight;
    }
}`
add listener to RecyclerView:
`view.getViewTreeObserver()
                  .addOnGlobalLayoutListener(new OnViewGlobalLayoutListener(view));`

**Comment by wpq2014** [comment]
@thagikura It should be `maxVisibleLines`, not `maxLines`
![maxVisibleLines](https://user-images.githubusercontent.com/6477207/81712572-55505a00-94a7-11ea-86d2-abfaafd62f19.png)

**Comment by 7LPdWcaW** [comment]
How do I use `maxLine` whilst preserving item widths? I am essentially trying to achieve the above; add all items to wrap but only show the first line but setting `maxLine` squishes all items onto 1 line
