### ISSUE TITLE
LICENSE file contains placeholders

### ISSUE THREAD

**Issue by kassens** [google/flexbox-layout#16]
[LICENSE, line 190](https://github.com/google/flexbox-layout/blob/63daec58fa04b56ad57845f6406a5c7867e9a30e/LICENSE#L190):

```
Copyright [yyyy] [name of copyright owner]
```

**Comment by thagikura** [comment]
The placeholders are also part of the license statement of Apache License 2.0.
See http://www.apache.org/licenses/LICENSE-2.0
