### ISSUE TITLE
denominator is calculated incorrect when JustifyContent is space_between/space_around

### ISSUE THREAD

**Issue by Shuijwan** [google/flexbox-layout#162]
in layoutHorizontal/layoutVertical, when JustifyContent is space_between/space_around, the 
float denominator = flexLine.getItemCount() !=1 ? flexLine.getItemCount() - 1 : 1f;

getItemCount() includes the GONE child, which will result in incorrect spaceBetweenItem.  It seems we should filter the GONE child?

**Comment by thagikura** [comment]
Thanks for reporting it!

You are right. In calculating the denominator, the number of GONE items count needs to be filtered out from the item count in a flex line.

Marking this as a bug.
