### ISSUE TITLE
Scroll?

### ISSUE THREAD

**Issue by qwill** [google/flexbox-layout#186]
I've populated my flexbox beyond the screen size... how do i scroll it ?

**Comment by thagikura** [comment]
Like other views you can scroll it f you wrap it with a ScrollView.

But the number of items is large, I'd suggest to use the FlexboxLayoutManager in the RecyclerView as in this [issue](https://github.com/google/flexbox-layout/issues/2).
The FlexboxLayoutManager isn't launched yet, but I'm going to launch the alpha version of it anytime soon.
