### ISSUE TITLE
Getting an empty list of FlexLines after adding views

### ISSUE THREAD

**Issue by yairopro** [google/flexbox-layout#195]
Hello
I tried to make a custom view, which extends the `FlexboxLayout`, where I set a list of Strings (`myCustomView.setListString(List<String> myList)`) and then I add a `TextView` for each element using `addView(View view)` method from inside the custom view.
While I add views programaticaly to the `FlexboxLayout`, I need to check each time the number of `FlexLine`. But `getFlexLines()` **returned always an empty list**.
So maybe i missunderstood the meaning of the method. Then I tested to toast the number of flexlines in a `OnClickListener`, and it worked great. It was corresponding to the number of lines I was seeing on the screen.
I don't understand then why it returns an empty list in the custom view.

**Comment by thagikura** [comment]
Hello, 

Thanks for reporting this.
Did you call super.onMeausre in your custom view's onMeasure method?
FlexboxLayout constructs the flex lines in the onMeasure method, so there might be a chance that you don't the super method in it.

**Comment by yairopro** [comment]
Thanks for the warning. :)
But I didn't override onMeasure method.
I had the child views in the setter method.

**Comment by thagikura** [comment]
Ok so is it possible to see your custom view code in some way?

**Comment by thagikura** [comment]
If you don't want to post it publicly, I appreciate if you can send me privately.

**Comment by yairopro** [comment]
Sure.
The purpose of the view is to display a list of tags (strings). The view can be "open" or "closed".
Open : It can display all the tags.
Closed : it can display tags only on the first line.

```java
public class TagsView extends FlexboxLayout {
	private List<String> _tags = new ArrayList<>();
	private boolean _open;

	// --- constructors ---
	public TagsView(Context context) {
		super(context);
		init(context, null);
	}
	public TagsView(Context context, AttributeSet attrs) {
		super(context, attrs);
		init(context, attrs);
	}
	public TagsView(Context context, AttributeSet attrs, int defStyleAttr) {
		super(context, attrs, defStyleAttr);
		init(context, attrs);
	}

	private void init(Context context, AttributeSet attrs){
		TypedArray typedArray = ViewUtils.getTypedArray(context, attrs, R.styleable.TagsView);
		try {
			_open = typedArray.getBoolean(R.styleable.TagsView_open, true);
		}
		finally {
			typedArray.recycle();
		}
	}

	@Override
	protected void onFinishInflate() {
		super.onFinishInflate();
		setFlexDirection(FLEX_DIRECTION_ROW);
		setFlexWrap(FLEX_WRAP_WRAP);
		setJustifyContent(JUSTIFY_CONTENT_FLEX_START);
		setAlignItems(ALIGN_ITEMS_FLEX_START);
		setAlignContent(ALIGN_CONTENT_FLEX_START);
		refresh();
	}

	/**
	 * Refresh the view.
	 */
	private void refresh(){
		int i = 0;

		// pass through all child views.
		for (i = 0; i < getChildCount(); i++) {
			if (i < _tags.size()) { // bind the tag to the child TextView
				TextView tagView = (TextView) getChildAt(i);
				String tag = _tags.get(i);
				tagView.setText("#" + tag);
			} else { // no more tag to add. Clear views left
				removeViews(i, getChildCount() - i);
				break;
			}
		}

		// check if it left tags without view
		while (i < _tags.size() && (_open || hasOneLine()) ) {
			// there was no enough child text view. Add news
			TextView tagView = (TextView) ViewUtils.inflate(R.layout.view_tags_item, this);
			tagView.setText("#" + _tags.get(i));
			addView(tagView);
			i++;
		}

		if (!_open && !hasOneLine()) {
			// remove last view
			removeViewAt(getChildCount()-1);
		}
	}

	/**
	 * Check if the view has one line or more.
	 */
	private boolean hasOneLine(){
		return getFlexLines().size() <= 1;
	}

	/**
	 * @return The list of tags.
	 */
	@NonNull
	public List<String> getTags() {
		return _tags;
	}

	/**
	 * Set the list of tags.
	 * @param tags List of tags to set. A null value, is like an empty list.
	 */
	public void setTags(@Nullable List<String> tags) {
		if (tags != null)
			_tags = tags;
		else
			_tags = new ArrayList<>();

		refresh();
	}

	/**
	 * @return True if the view is open. False if it closed.
	 */
	public boolean isOpen() {
		return _open;
	}

	/**
	 * Close/open the view.
	 * @param open True to open the view. False to close it.
	 */
	public void setOpen(boolean open) {
		if (_open != open) {
			_open = open;
			refresh();
		}
	}
}
```

**Comment by yairopro** [comment]
The method `hasOneLine()` always returns 0.
I placed a breackpoint to check the content of the list, and it is empty.

**Comment by thagikura** [comment]
Hi, thanks for pasting your code.

I investigated the result of the getFlexLines method and no issues were found.

It looks like you are calling getFlexLines() only within the onFinishInflate method.
So when the getFlexLines method is called, the measure phase hasn't completed, it means the flex lines haven't been created yet.

Also note that if you call the addView method programatically, the result of the getFlexLines will not be reflected in the same frame (within the same method) because the onMeasure method should be called in the next layout pass (when the app becomes idle. That behavior is not specific to FlexboxLayout, but applies to all other layouts as well)

The most simple code to check the result of getFlexLines method is as follows. You can put this kind of Button and the onClickListener in your Activity. Then you can verify getFlexLines() returns the flex lines previously constructed before clicking the button.

```java
findViewById(R.id.add_button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                TagsView tagsView = (TagsView) findViewById(R.id.tagview);
                TextView textView = (TextView) getLayoutInflater()
                        .inflate(R.layout.view_tags_item, null);
                tagsView.addView(textView);

                Log.d(MainActivity.this.getClass().getSimpleName(), "Flex line count: " + tagsView.getFlexLines().size());
            }
        });
```

**Comment by yairopro** [comment]
I did not know onMeasure was not called on the same frame (you taught me something =) ).
Thanks a lot!
