### ISSUE TITLE
why not add a callback can get flex lines by realtime

### ISSUE THREAD

**Issue by 328629033** [google/flexbox-layout#197]
As the title and I have seen the issue 195,why not notify developer line count has changed automatically ? It 's just a suggestion, of course there have been many scenes I used it.

**Comment by thagikura** [comment]
Hi 

Actually developers can easily detect a line count change by comparing the result of the getFlexLines method. 
The reason the count of the flex lines wasn't changed in the #195 was that, the reporter of the issue called the getFlexLines method in the same method (same frame) of adding flex items in the FlexboxLayout, which can be easily avoided.

**Comment by 328629033** [comment]
I don't understand very well, when should I call getFlexLines method, like code below
`mFlexboxLayout.addView(textView);`
and get the real line count?

**Comment by thagikura** [comment]
You can get the real count of the flex lines after you call like `mFlexboxLayout.addView(textView);`

But the point is if you call getFlexLines and addView in a same method, the measurement of the FlexboxLayout hasn't started when you call getFlexLines method, thus at that time, the result of the getFlexLines isn't reflected.

So you need to call the getFlexLines in a following frame (not in the same method)

**Comment by 328629033** [comment]
I got it, thanks so much.
