### ISSUE TITLE
[RecyclerView] Calculated flex lines should be discarded when handling configuration changes manually

### ISSUE THREAD

**Issue by thagikura** [google/flexbox-layout#198]
When developers handle configuration changes by themselves, (e.g. adding the attribute in the AndroidManifest `android:configChanges="orientation|keyboardHidden"`)
the flex lines before the anchor position needs to be discarded otherwise the length of the prior lines may not match the new screen size.

**Comment by thagikura** [comment]
One solution I can think of is that FlexboxLayoutManager exposes an API that clears the state of the flex lines state and have developers that handle configuration changes manually call the API in the `onConfigurationChange` method.

**Comment by ramsedsay** [comment]
Flex lines what is determonology for this?

**Comment by thagikura** [comment]
I'm referring to [this](https://www.w3.org/TR/css-flexbox-1/#flex-lines) as the Flex line terminology.

**Comment by thagikura** [comment]
Fixed by #201
