### ISSUE TITLE
[RecyclerView] no items are shown when the RecyclerView is wrapped inside a ScrollView.

### ISSUE THREAD

**Issue by LetaiefAymen** [google/flexbox-layout#199]
Hi :), i made a test with the demo-cat-gallery , if the RecyclerView is inside a ScrollView then no items are shown at all for devices with Api level 21 (maybe lower API too), it works on API level 24, and it's easily reproducible.

**Comment by eikaramba** [comment]
Also happens on lower API levels....

**Comment by thagikura** [comment]
Hi @LetaiefAymen, @eikaramba 

Oops, sorry for that.
Let me take a look at this.

**Comment by ramsedsay** [comment]
I'm on a 28 or higher;

**Comment by thagikura** [comment]
Hi, 

After some investigation, found that if you add `android:fillViewport="true"` to the parent ScrollView, the items in the RecyclerView should be shown with the FlexboxLayoutManager.

```xml
<ScrollView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/scrollview"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fillViewport="true" >
        <android.support.v7.widget.RecyclerView
            android:id="@+id/recyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>
</ScrollView>
```

I'm wondering in what use case, RecyclerView in a ScrollView needed?
The solution above should work, but the RecyclerView doesn't recycle the views off the screen if you do so.
It's not recommended that you use a ListView (the document says ListView, but also applies to RecyclerView) in a ScrollView as explained in the [Javadoc](https://developer.android.com/reference/android/widget/ScrollView.html)

**Comment by LetaiefAymen** [comment]
Hi again :),
I just tried to provide you a simple use case where the items are not shown, and setting the fillViewport fix the issue in that use case but not in our use case.
Here is an overview on our use case :
![image](https://cloud.githubusercontent.com/assets/5459768/23212568/9dc0d3e4-f907-11e6-90de-189e5407bbf6.png)
I had to use a NestedScrollView in case the view gets bigger than the screen height, 
currently i had to revert to StaggeredGridLayoutManager (like shown on the picture above), and changing the layout manager to FlexboxLayoutManager result to not showing the items at all (but it works fine with StaggeredGridLayoutManager even without adding the attribute android:fillViewport="true" to the NestedScrollView). if i set the RecyclerView to have a static width or minWidth it shows the elements but i have to scroll inside the RecyclerView to see all the items (which is not the desired result), setting the flexDirection to FlexDirection.COLUMN result in showing all the elements but not if the flexDirection is set to FlexDirection.ROW.

Since the normal LayoutManager are working fine but not the FlexboxLayoutManager , i guess that it might be a problem in the library (but i am not sure), as it should provide the same result in those specific conditions.

I hope you have a better idea about the issue in our use case :), especially that it is working fine on Api 24 or higher (so i could see all the items) but not on api 22 or lower.
I guess another choice for me would be to use the normal flexbox-layout and get rid of the RecyclerView but that would need some refactoring.

**Comment by thagikura** [comment]
Hi @LetaiefAymen,

Thanks for the detailed clarification.
Looks like you are using the Flexbox as a structure for tags, so I highly recommend you to use FlexboxLayout instead of FlexboxLayoutManager for that use case because:
 - I guess the number of items is not going to be so large (like no less than 40)
 - FlexboxLayout is more stable than the alpha version of the FlexboxLayoutManager
 - Even if you use the StaggeredGridLayoutManager, the number of the columns can't be changed dynamically, so I think you need to handle the number of columns depending on the width of the screen, which should be automatically taken care of if you use FlexboxLayout.

From looking at the behavior I think it's issue with the FlexboxLayoutManager, I still haven't spotted what part causes that.
So let me keep this issue open.

**Comment by thagikura** [comment]
Looks like this is fixed by #235.

I'll release a new alpha version anytime soon.
Please reopen it if there is still an issue.

**Comment by Fhaldini** [comment]
![asd](https://user-images.githubusercontent.com/29018772/31159809-ec12395e-a8f5-11e7-96cf-d9ef0147bc6e.PNG)

any help me now... pls...

**Comment by Soumyajit2101999** [comment]
RecyclerView.setHasFixedSize(false);
