### ISSUE TITLE
Default ProgressBar changed with RecyclerView

### ISSUE THREAD

**Issue by rushank** [google/flexbox-layout#202]
Default colorAccent progress bar is changed if we use  the   com.google.android:flexbox:0.3.0-alpha2'dependencies with recyclerview

And it works perfect with version '0.2.5'.

**Comment by thagikura** [comment]
Hi,

Thanks for reporting.
I couldn't reproduce it on my end.
Could you share your relevant piece of code?

**Comment by thagikura** [comment]
Please re-open it if this still persists.
