### ISSUE TITLE
FlexBoxLayoutManager Scrolling Issue

### ISSUE THREAD

**Issue by eygraber** [google/flexbox-layout#206]
I have a `RecyclerView` that has a `FlexboxLayoutManager` (as `new FlexboxLayoutManager(FlexDirection.ROW)`). 

When I add an item to the `RecyclerView` I want to scroll to the newest item using `scrollToPosition(adapter.getItemCount() - 1)`.

The problem is that when I do that, after filling a line, the next scroll causes the first column of the last row to scroll to the top of the `RecyclerView`, and the rest of the `RecyclerView` is filled with empty space so all the items above it are scrolled off the screen.

You can see this behavior in the sample app of [this library that uses `FlexboxLayoutManager` (in the `flexbox` branch)](https://github.com/isapp/chips/tree/flexbox). Just click the FAB to start adding items.

**Comment by thagikura** [comment]
Thanks for reporting it and even a sample project!
Let me take a look.

**Comment by eygraber** [comment]
@thagikura any news?

**Comment by thagikura** [comment]
Found that there was an issue in the layout logic when scrollTo position was called with a new item in the adapter.

I'll released a fixed version anytime soon.

**Comment by spocky** [comment]
May I add that this issue isn't only related to new elements ?
Say that you have more than a full screen page of items in your recycler. If you don't see the last line of items and scrollToPosition items.count-1 (or any other item on the last line), the same behavior can be seen (last line scrolls to the top and everything else goes offscreen).
The opposite is also true : if first line is offscreen and you scrollToPosition 0, the first line will be displayed at the screen bottom and everything above will be blank.

**Comment by thagikura** [comment]
Hi,

Thanks for the update.
This should be fixed by #231.

**Comment by thagikura** [comment]
Should be fixed by #231.
