### ISSUE TITLE
layoutManager.setAlignContent(AlignContent.FLEX_START);

### ISSUE THREAD

**Issue by jxc02** [google/flexbox-layout#211]
When will this be implemented? Is there any way around it? I need my layoutManager Align Content to be Flex_Start, NOT Stretch! Thank you.

**Comment by thagikura** [comment]
alignContent expects the flex container to have a fixed size, which can't be true for RecyclerView.
So it's not going to be implemented.

Do you happen to mean alignItems instead of alignContent?
If so setting AlignItems.FLEX_START is supported.

**Comment by thagikura** [comment]
Please re-open it if it doesn't answer your question.
