### ISSUE TITLE
There's no methods to get visible items position?

### ISSUE THREAD

**Issue by mturki** [google/flexbox-layout#217]
Unlike some others LayoutManagers (LinearLayoutManager, StaggeredGridLayoutManager, GridRecyclerViewListFragment) there is no findFirstCompletelyVisibleItemPosition, findLastCompletelyVisibleItemPosition, findLastVisibleItemPosition or similar methods?

**Comment by thagikura** [comment]
They are not implemented yet. 
It can be impelemented in the future.

**Comment by thagikura** [comment]
Fixed by #245
