### ISSUE TITLE
Remove appcompat-v7 dependency

### ISSUE THREAD

**Issue by commonsguy** [google/flexbox-layout#220]
Your `flexbox/build.gradle` file has a dependency on `appcompat-v7`. However, you do not appear to be using this library. Since `appcompat-v7` adds ~1MB to an app, and not every app uses `appcompat-v7`, it would be nice if you removed that dependency, or replaced it with something more focused (e.g., `support-compat`) that matches what you actually need.

Thanks!

**Comment by thagikura** [comment]
Good point. Thanks for pointing this out. The library depends on some of the compat parts, let me change tge dependency to a focused one.
