### ISSUE TITLE
Trying to mimic Google Photos app using FlexboxLayoutManager

### ISSUE THREAD

**Issue by donpwilson** [google/flexbox-layout#224]
I am implementing this layout manager as an option in my photo manager app and trying to set it up to mimic the Google Photos app but so far without complete success.

I played with the demo cat gallery which on the face of it shows the correct behaviour. However as I'm sure you are aware, it uses centreCrop on the imageView to give the correct visual effect but at the expense of cropping images. 

I changed centreCrop to fitCenter to see the effect. If everything else is correct, this setting should leave no blank space between photos.

In CatViewHolder I also replaced:
 `flexboxLp.setFlexGrow(1.0f);`
with:
`      flexboxLp.setHeight(200);
            flexboxLp.setWidth(flexboxLp.getHeight()*drawable.getIntrinsicWidth()/drawable.getIntrinsicHeight());
     `

This gives quite a neat implementation but all the rows are (obviously) the same height. The step that is missing is to stretch the photos in each row "proportionately" and maintaining aspect ratios so that the height of the row is increased as necessary to clear all the space between photos.

Is there a way to achieve this or is it on your "to do" list? I suspect that it is outside scope because, as far as I can see, it is not covered in the underling Flexbox specs.

**Comment by thagikura** [comment]
Hi,

I think your suggestion can be rephrased by if FlexboxLayout supports specifying an aspect ratio.
Currently that is not in the to do list nor the original Flexbox specification doesn't have that.

But I could be convinced if it's worth adding support even if not defined in the original CSS spec (e.g. the `layout_wrapBefore` attribute).

However it's not going to be prioritized given that there are some other outstanding issues.

**Comment by donpwilson** [comment]
As I thought would be the case. No problem!

**Comment by vipulasri** [comment]
@thagikura Will this feature ever be supported? Please provide an update.
