### ISSUE TITLE
The first line disappears

### ISSUE THREAD

**Issue by xiaozhuge007** [google/flexbox-layout#228]
Slide first line disappear  @link FlexboxLayoutManager

**Comment by thagikura** [comment]
I think this is duplicate of #206 is that correct?

**Comment by justplay1** [comment]
@thagikura I also have this bug, it's not a problem with scrollToPosition

**Comment by xiaozhuge007** [comment]
@thagikura Sliding occurs when the first line of item is less than second lines
CatGallery Demo has the same problem and the first line will disappear

**Comment by xiaozhuge007** [comment]
If the first line of item is greater than second lines, this bug will not appear

**Comment by thagikura** [comment]
Reproduced it on my end. Taking a look.

Thanks for reporting the issue!

**Comment by thagikura** [comment]
Fixed by #234

**Comment by justplay1** [comment]
@thagikura When release this fix?

**Comment by thagikura** [comment]
@justplay1 hopefully next week.
