### ISSUE TITLE
Is Google planning to include it in the official Android?

### ISSUE THREAD

**Issue by GiwonJang** [google/flexbox-layout#23]
Is Google planning to include this in the Android Support Library or SDK?

**Comment by thagikura** [comment]
Not planning to do so at this moment.

If added to the SDK, there will be a backward compatibility issue.
If added to the support library, the backward compatibility issue doesn't happen, but anyway the installation requires a one line in the dependency in both ways.
The library is still in an early stage, I found it more beneficial to leave is as a standalone library for a quick iteration.

**Comment by GiwonJang** [comment]
@thagikura OK, Thanks your comment.
