### ISSUE TITLE
Dynamically added fragment w/seekbar shrinks

### ISSUE THREAD

**Issue by ghorkov32** [google/flexbox-layout#237]
Hi, i'm dynamically adding fragments with FragmentTransaction, and the seekbar inside shrinks, leaving something like this:
![screenshot_1490707805](https://cloud.githubusercontent.com/assets/22202372/24407555/a654b098-13a1-11e7-8698-9350bb21967c.png)

i want the fragment to respect the minimum width (already tried setting it in the fragment layout) with the seekbar not wrapping. No matter what i do (setting the minimum width and setting the flexGrow property), the seekbar will always wrap.

I'll share the code used in the layout and my fragment.

Fragment:

`public class StatSeekbarFragment extends Fragment implements View.OnClickListener {

    private SeekBar statSeekBar;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View viewToReturn = inflater.inflate(R.layout.stat_seekbar, null);
        /*LayoutParams from Flexbox tested here, didn't work*/
        return viewToReturn;
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        statSeekBar = (SeekBar) view.findViewById(R.id.statSeekBar);
        statSeekBar.setMax(Constants.SEEKBAR_MAX_DEFAULT);
        statSeekBar.setProgress(Constants.SEEKBAR_MAX_DEFAULT);

        view.findViewById(R.id.addButton).setOnClickListener(this);
        view.findViewById(R.id.substractButton).setOnClickListener(this);
        view.findViewById(R.id.changeButton).setOnClickListener(this);
    }

    @Override
    public void onClick(View view) {
        switch (view.getId()) {

             /*TODO Implement*/
        }
      }`

Fragment Layout:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="380sp"
    android:layout_height="50sp"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    app:layout_flexGrow="1">

    <SeekBar
        android:id="@+id/statSeekBar"
        style="@style/Widget.AppCompat.SeekBar.Discrete"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="center_vertical"
        android:layout_weight="75"
        android:max="10"
        android:progress="3" />

    <Button
        android:id="@+id/addButton"
        style="@style/Widget.AppCompat.Button.Small"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:text="+" />

    <Button
        android:id="@+id/substractButton"
        style="@style/Widget.AppCompat.Button.Small"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:text="-" />

    <Button
        android:id="@+id/changeButton"
        style="@style/Widget.AppCompat.Button.Small"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_weight="1"
        android:text="Δ" />
</LinearLayout>`

Flexbox container layout 
```

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/general_container"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.puszkiapps.app.MainActivity"
    tools:showIn="@layout/app_bar_main">
 <ScrollView
     android:layout_width="match_parent"
     android:layout_height="match_parent">
    <com.google.android.flexbox.FlexboxLayout
        android:id="@+id/fragment_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:flexWrap="wrap">

    </com.google.android.flexbox.FlexboxLayout>
 </ScrollView>
</LinearLayout>
```

FAB Code (to add fragments):

`            

                android.support.v4.app.FragmentManager fragmentManager = getSupportFragmentManager();

                android.support.v4.app.FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();

                StatSeekbarFragment newSeekBarFragment = new StatSeekbarFragment();

                fragmentTransaction.add(R.id.fragment_container, newSeekBarFragment, "seekbar with buttons");

                fragmentTransaction.commit();
            
`

So the question is: am i doing something wrong or is there anything else to try? or can this be a bug?

Thanks in advance :)

**Comment by thagikura** [comment]
Need more info, could you share the attributes for views inside the FlexboxLayout?

Your FlexboxLayout looks like this?
 FlexboxLayout
   - fragment
   - fragment

or like this?

FlexboxLayout
  - Seekbar
  - Button
  - Button
  - Button
  - Seekbar
  - Button
  - Button
  - Button

**Comment by ghorkov32** [comment]
Hi Takeshi, thanks for your reply!

Regarding this

> Need more info, could you share the attributes for views inside the FlexboxLayout?

The layout and fragment code are in the first post, do you need info at debug level? Or the fragment creation code?

> Your FlexboxLayout looks like this?

Looks like the first option (the one with two fragments). These fragments are dynamically added with the FAB.

NOTE: last night i found a workaround to this, i've set the buttons, below the seekbar, and left of the buttons a textview with a fixed size. I've tested the app on a phone emulator and a tablet emulator, and it works wonderfully, but in the future i'll have the need to add single line seekbars with buttons on the right, that's why i'm not closing the issue yet (sorry :( )

Regards,

**Comment by thagikura** [comment]
Ok so could you share the entire xml of the R.layout.stat_seekbar file? 

I think there is another root layout in that file used as the Fragment (otherwise the layout xml structure is not valid).
If so, that root layout is the direct child of the FlexboxLayout.

**Comment by thagikura** [comment]
Hi @ghorkov32, any update on this?

**Comment by thagikura** [comment]
Please re-open the issue if this issue still persists.
