### ISSUE TITLE
Find visible item bound indexes?

### ISSUE THREAD

**Issue by eneim** [google/flexbox-layout#243]
Can I have the same thing of so-called "LinearLayoutManager findFirstVisibleItemPosition() and findLastVisibleItemPosition()" ?

I see there are mFirstIndex and mLastIndex of each FlexLine, as well as there is no information about if a FlexLine is visible or not. Applying the access to those state may help ...

Thanks.

**Comment by thagikura** [comment]
Yes, implementing those methods like find...VisibleItemPosition is under the works as #217.

Let me close this one.
