### ISSUE TITLE
use style.xml

### ISSUE THREAD

**Issue by janicelco** [google/flexbox-layout#247]
Please add this feature to reuse styles. I have tried it but got a warning
`    <style name="flexboxSortFilter">
        <item name="android:layout_width">match_parent</item>
        <item name="android:layout_height">wrap_content</item>
        <item name="app:flexWrap">wrap</item>
        <item name="app:flexDirection">row</item>
        <item name="app:alignItems">flex_start</item>
        <item name="app:alignContent">flex_start</item>
        <item name="app:justifyContent">flex_start</item>
        <item name="app:showDividerVertical">middle|end</item>
        <item name="app:dividerDrawableVertical">@drawable/ic_divider</item>
        <item name="app:showDividerHorizontal">middle</item>
        <item name="app:dividerDrawableHorizontal">@drawable/ic_divider_horizontal</item>
    </style>`

`No resource found that matches the given name: ...`

**Comment by thagikura** [comment]
Custom styles should be defined in each app, not in the library.
Let me close this.

**Comment by janicelco** [comment]
Yes. I have defined it in the app. But it seems that Android Studio is not recognising this resource name "app:flexWrap" etc on runtime. No issues show on styles.xml till trying to run.

**Comment by thagikura** [comment]
You don't have to add the `app` namespace in the styles.xml.
Please just specify like 

```xml
    <style name="FlexContainer" >
        <item name="flexWrap">wrap</item>
    </style>
```

**Comment by janicelco** [comment]
Got it! Thanks!!!
