### ISSUE TITLE
Add support for scrollbars in FlexboxLayoutManager

### ISSUE THREAD

**Issue by Saketme** [google/flexbox-layout#249]
I just noticed that `FlexboxLayoutManager` does not override `computeVerticalScrollRange()` and `computeVerticalScrollExtent()` that are required for drawing scrollbars. Additionally, I cannot use `View#canScrollVertically()` either to check if the list can be scrolled further because it internally calls the same two methods.

Will it be possible to add support for this?

**Comment by thagikura** [comment]
Thanks for bringing this up.
Yes, that should be supported. I'll keep this issue as an enhancement.

**Comment by Saketme** [comment]
Thank you!

**Comment by thagikura** [comment]
Fixed by #272
