### ISSUE TITLE
LayoutManager: child views are not measured properly when they are not visible

### ISSUE THREAD

**Issue by Saketme** [google/flexbox-layout#262]
Hey @thagikura I found a visual bug.

Steps to reproduce: 
- Make changes to a RecyclerView's data-set that are currently not visible.
- Dispatch the updated dataset to the RV's adapter.
- Scroll to items that were changed, but were not visible when the change was triggered

#### Screenshot

![bug](https://cloud.githubusercontent.com/assets/2387680/25071842/cf15c8e0-22de-11e7-9225-54215bc4f02d.png)

`AntrixCorporation -> Antri, AskReddit -> Ask, bangalore -> banga, chemicalreactiongifs -> chemi`

In my layout, I have an animation that changes the RV's height and this bug gets fixed as soon as the animation is run.

**Comment by thagikura** [comment]
Thanks for filing this. What part did you to the items that were not visible?
Did you change the texts?

Anyway this looks like an issue.

**Comment by Saketme** [comment]
No, I simply inserted a new item.

**Comment by thagikura** [comment]
Ok I found the issue.
Non-visible part of the flex container is not computed currently. There needs to be like a dirty flag telling that that part needs to be computed.

**Comment by Saketme** [comment]
Awesome!

**Comment by thagikura** [comment]
Fixed by #269.

I'll release it in the next alpha version.
