### ISSUE TITLE
LayoutManager: clipToPadding=false is buggy

### ISSUE THREAD

**Issue by saket** [google/flexbox-layout#263]
Is it a known issue that items that aren't fully visible don't show up when they're within the padding area and clipToPadding is set to false with a certain padding amount?

**Comment by thagikura** [comment]
No it's not a known issue. Do you have a code that can reproduce the issue?
Thanks in advance.

**Comment by Saketme** [comment]
Sure, I will try sending a sample project to help you reproduce this.

**Comment by matecode** [comment]
I have the same problem

To reproduce use a RecyclerView. The important part is that you turn off clipToPadding and set a padding at bottom.
```
    <android.support.v7.widget.RecyclerView
            android:id="@+id/recycler_az_content"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_gravity="center_horizontal"
            android:layout_marginRight="8dp"
            app:layout_constraintRight_toRightOf="parent"
            android:layout_marginLeft="8dp"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintHorizontal_bias="0.0"
            android:layout_marginTop="8dp"
            app:layout_constraintTop_toBottomOf="@+id/recycler_az"
            app:layout_constraintBottom_toBottomOf="parent"
            android:clipToPadding="false"
            android:paddingBottom="64dp"
            android:layout_marginBottom="0dp"/>

```
Here I set clipToPadding = false and botomPadding of 64dp

The I use 

```
        FlexboxLayoutManager flexLayoutManager = new FlexboxLayoutManager(context);
        flexLayoutManager.setFlexDirection(FlexDirection.ROW);
        recyclerAZcontent.setLayoutManager(flexLayoutManager);
```

Normally the Recycler should draw its items also in the padding area. The FlexBoxLayoutManager is drawing when the item moves out of padding area. So the effect is that items suddenly appear.

**Comment by matecode** [comment]
For better understanding i recorded a little video. If you look at the bottom recyclerview, you can see item appearing suddenly when i scroll down, but they keep drawn when recycler is moved up again
![ezgif-4-d38b7b0ba1](https://user-images.githubusercontent.com/3225274/31185874-67741888-a92d-11e7-9b57-a22d6203fdba.gif)

**Comment by thagikura** [comment]
Thanks for the video. Looks like this is because FlexboxLayoutManager doesn't support predictive item animations yet ([example](http://frogermcs.github.io/recyclerview-animations-androiddevsummit-write-up/)).

I tried to implement it, but haven't completed it.
Let me keep this open for until we implement it.

**Comment by matecode** [comment]
Any news on this topic?

**Comment by Gericop** [comment]
Any news? Having the same problem.

**Comment by Samuel-Unknown** [comment]
I have the same problem.

**Comment by GeoffGodwin** [comment]
I get a similar problem though at the top when using this in conjunction with a coordinator layout. I have padding atop the RecyclerView, scrolling down is fine but when I return to the top the recycler doesn't redraw any of the top items while they'd be within the padding.

**Comment by RadiationX** [comment]
Any news? Having the same problem.

**Comment by 1240** [comment]
after 2 years, any news ?

**Comment by trinhcu18** [comment]
I have the same problem, RecyclerView + FlexLayoutManager inside ConstraintLayout and clipToPadding not work at first show. I change layout_height from 0dp to wrap_content then it works

**Comment by Qhash** [comment]
I have the same problem.
