### ISSUE TITLE
Layout not shrink with ScrollView

### ISSUE THREAD

**Issue by iferrant** [google/flexbox-layout#265]
I am designing a layout with image and text in which both fill no more than the screen size, for this the image shrinks according to the need of the text. Right now the view hierarchy is as follows:

- Scrollview
  - FlexboxLayout (1)
    - FlexboxLayout (2)
      - ImageView
    - FlexboxLayout (3)
      - TextView

The FlexboxLayout (1) `direction` is setted as column, the properties of FlexboxLayout (2) are `grow = 1` and `shrink = 1` and those of FlexboxLayout (3) are `grow = 1` and `shrink = 0`.
The problem is that the image only shrinks to its original resolution, when the desired behavior would be to shrink and disappear if the text needs to grow. I suppose the problem is to have a ScrollView as the parent of FlexboxLayout (1), making the properties of  the ScrollView more important than the flexbox shrink property.
Is this a known behavior? Is there any solution for the desired behavior?

**Comment by thagikura** [comment]
If you wrap the layout with ScrollView, FlexboxLayout thinks its height as UNSPECIFIED, so setting the flex_shrink isn't going to work.

If you need to shrink a view inside the FlexboxLayout, you can't wrap it with ScrollView.
By the way I think the FlexboxLayout in the second level is not needed.
I think you can do like

```
FlexboxLayout
  - ImageView
  - TextView
```

**Comment by thagikura** [comment]
Closing. Please reopen it if you think there is an issue.
