### ISSUE TITLE
mOrderCache's value is never changed

### ISSUE THREAD

**Issue by thetran84** [google/flexbox-layout#266]
mOrderCache is supposed to store the previous order of all childView, but its value is never changed at runtime when I tried to swap the order of 2 childViews. 
In file FlexboxLayout.java, line 472, I tried to change it like this and it fixed the issue.
mOrderCache.append(order.index, order.order);

**Comment by thagikura** [comment]
Thanks!
You are right. The line 472 should be 
`mOrderCache.append(order.index, order.order);`

I'm going to fix it.

**Comment by thagikura** [comment]
Fixed by #267

**Comment by thetran84** [comment]
When can I expect to get the version 0.2.7 released?

**Comment by thagikura** [comment]
Not too long. Looks like there are no other pending issues.
Thanks for poking.
