### ISSUE TITLE
Calculate view size taking into account dividerDrawable size

### ISSUE THREAD

**Issue by friendoye** [google/flexbox-layout#271]
That would be great to have an option for FlexboxLayout to calculate view size, that uses attribute "layout_flexBasisPercent", based on parent's size minus total size of dividers, that are used in either horizontal or vertical directions.
What do you think?

**Comment by thagikura** [comment]
Hi, 

Thanks for your suggestion. However, I think dividers are part of the FlexboxLayout and I don't still come up with an use case where that addition is particularly useful.

Is there a specific use case in your mind?

**Comment by friendoye** [comment]
Sorry for delay.

Let's imagine, that I want to have 5 TextView's and want it to be aligned like so: 
*----------------*      *----------------*
|         1 (50%)      |       |         2 (50%)      |
*----------------*      *----------------*
*----------------*      *----------------*
|         3 (50%)      |       |         4 (50%)      |
*----------------*      *----------------*
*--------------------------------------*
|                          5 (100%)                        |
*--------------------------------------*
If I add vertical divider, than all my views will start from new line and that's a pity ;(
I can fix this with adding extra padding/margin to TextView, but it seems like a very hacky solution for me. Isn't this problem intended to be solved by FlexboxLayout itself?

**Comment by thagikura** [comment]
If you set the attributes like above, the second item will be on the second line at this moment.
But you can achieve almost the same thing by setting like:

1:
  layout_flexBasisPercent="40%"
  layout_flexGrow="1"

2:
  layout_flexBasisPercent="40%"
  layout_flexGrow="1"

3:
  layout_flexBasisPercent="40%"
  layout_flexGrow="1"

4:
  layout_flexBasisPercent="40%"
  layout_flexGrow="1"

5:
  layout_flexBasisPercent="80%"
  layout_flexGrow="1"

It will fill the remaining space even if you include the vertical dividers.

**Comment by thagikura** [comment]
I think the solution I commented works, please re-open it if you think there is still an issue.
