### ISSUE TITLE
FlexLayoutManager show nothing when I set RecyclerView different Padding  

### ISSUE THREAD

**Issue by 9h0st** [google/flexbox-layout#274]
```
mRecyclerView.setPadding(
                (int) getResources().getDimension(R.dimen.dp_5), 0,
                (int) getResources().getDimension(R.dimen.dp_5),
                (int) getResources().getDimension(R.dimen.dp_10));
FlexboxLayoutManager flexboxLayoutManager = new FlexboxLayoutManager();
flexboxLayoutManager.setFlexDirection(FlexDirection.ROW);
flexboxLayoutManager.setJustifyContent(JustifyContent.FLEX_START);
flexboxLayoutManager.setAlignItems(AlignItems.FLEX_START);
mRecyclerView.setLayoutManager(flexboxLayoutManager);
```
The padding_top and the padding_bottom are different, when I add one data for recyclerview to show, it works normally. But If I add more data, it shows nothing, I cannot see any item.
While I set padding top and bottom the same, it works normally.
I think FlexLayoutManager doesn't deal with this case well or maybe I use it the wrong way?

**Comment by thagikura** [comment]
Hi,

Thanks for reporting this.
But I couldn't reproduce it on my end by setting the different paddings.

Do you happen to have a test project that I can debug and test?

**Comment by thagikura** [comment]
Please reopen it if this issue still persists.
