### ISSUE TITLE
Failed to resolve: com.google.android:flexbox:0.2.6

### ISSUE THREAD

**Issue by wangpingtaohn** [google/flexbox-layout#277]
This is my app root gradle:
allprojects {
    repositories {
        jcenter()
    }
}
This is my app module gradle:
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    testCompile 'junit:junit:4.12'
    compile 'com.google.android:flexbox:0.2.6'

}

**Comment by thagikura** [comment]
Obviously this is not an issue with the library. Let me close.

Please use a copy of already working build.gradle file as a starting point.

**Comment by wangpingtaohn** [comment]
allprojects {
    repositories {
        jcenter{
           // add this line to solve
            url 'http://jcenter.bintray.com/'
        }
    }
}
