### ISSUE TITLE
bug with addItem

### ISSUE THREAD

**Issue by wekin** [google/flexbox-layout#280]
if add position less then firstVisiblePosition, the viewType is error

**Comment by wekin** [comment]
"... add: 7" is position to add, but it getItemViewType for position 70
getItemViewType add: 7
getItemViewType: 70

getItemViewType add: 8
getItemViewType: 113

**Comment by thagikura** [comment]
Hi @wekin,

Sorry, the issue wasn't clear do you have a example project to share that can reproduce the issue?

**Comment by wekin** [comment]
@thagikura
FlexboxLayoutManager is not support multiType for adapter well;
it is easy to get error type for a invisible position to add a item;

**Comment by wekin** [comment]
@thagikura
the test project is [https://github.com/wekin/test-flexlayout](url)

**Comment by thagikura** [comment]
Hi @wekin,

Thanks creating the example project!
Now I'm able to reproduce the issue.

I'll take a look.

**Comment by thagikura** [comment]
Should be fixed by #311
