### ISSUE TITLE
No resource identifier found for attribute'layout_flexDirection' in package 'android'

### ISSUE THREAD

**Issue by revathyramanan** [google/flexbox-layout#282]
Hi,
I am trying to use flexbox layout. I have added the dependency as mentioned in your code.
compile 'com.google.android:flexbox:0.2.1'
But I am unable to use any of its attributes.  When I use the layout with 4 items, the items are evenly distributed over the screen with "row" direction. But when I add the attribute android:layout_flexDirection = "column", no changes are being reflected. On building the project, I am getting the error as mentioned in the subject.
Could you please look into it?

Thanks,
Revathy

**Comment by thagikura** [comment]
Hi,

flexDirection is an attribute for the FlexboxLayout itself, not the attribute for its children.

So you need to specify like this
```xml
<com.google.android.flexbox.FlexboxLayout xmlns:app="http://schemas.android.com/apk/res-auto"
   app:flexDirection="column" />
```

Also 0.2.6 is the current latest stable version. Please update it.

**Comment by revathyramanan** [comment]
Hi,
Thank you so much for your prompt reply. I have added that line, but still
it throws me error. I did not have that attribute for the children. I have
it only for the flexbox layout itself.
I have tried adding xmlns:android attribute to flexbox as well. Still I
have got the error.

My dependencies:

compile 'com.google.android:flexbox:0.2.6'
compile "com.android.support:support-v4:${rootProject.ext.supportLibVersion}"
compile "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"

compile "com.android.support:recyclerview-v7:${rootProject.ext.supportLibVersion}"

compile "com.android.support:design:${rootProject.ext.supportLibVersion}

My SDK versions:

minSdkVersion = 14
targetSdkVersion = 25
compileSdkVersion = 25
buildToolsVersion = "23.0.2"
supportLibVersion = "25.3.1"
espressoVersion = "2.2.2"
testRunnerVersion = "0.5"
junitVersion = "4.12"



My XML Code:

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    >

    <include
        android:id="@+id/toolbar"
        layout="@layout/toolbar" />

    <com.google.android.flexbox.FlexboxLayout
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        android:layout_flexDirection="column"
        android:layout_below="@+id/toolbar"

        >



            <TextView
                android:id="@+id/textView10"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="TextView" />

            <EditText
                android:id="@+id/editText8"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:inputType="textPersonName"
                android:text="Name" />


            <TextView
                android:id="@+id/textView11"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:text="TextView" />

            <EditText
                android:id="@+id/editText9"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:ems="10"
                android:inputType="textPersonName"
                android:text="Name" />




        </com.google.android.flexbox.FlexboxLayout>




</RelativeLayout>




Thanks,
Revathy.

**Comment by revathyramanan** [comment]
Hey,
Sorry that I didn't notice that "app:flexdirection". I changed it and it
resolved the problem.

Thanks,
Revathy.
