### ISSUE TITLE
RecyclerView with SpacingItemDecoration issue

### ISSUE THREAD

**Issue by mina-william** [google/flexbox-layout#293]
Hi,
I use FlexboxLayoutManager with RecyclerView and SpacingItemDecoration.
It's ok when you don't scroll the RecyclerView. But if I start scrolling, the spacing between items misplaced.
```java
FlexboxLayoutManager layoutManager = new FlexboxLayoutManager();
        layoutManager.setFlexDirection(FlexDirection.ROW);
        layoutManager.setJustifyContent(JustifyContent.SPACE_BETWEEN);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setItemAnimator(new DefaultItemAnimator());
        
recyclerView.addItemDecoration(new SpacingItemDecoration(getResources().getDimensionPixelOffset(R.dimen.item_space),
                getResources().getDimensionPixelOffset(R.dimen.item_space)));
```

**Comment by mina-william** [comment]
Thanks, fixed by #294

**Comment by thagikura** [comment]
Oh thanks for checking!

**Comment by AndroidDeveloperLB** [comment]
@mina-william Where's the code for SpacingItemDecoration ? 
Can it handle spacing at the top, so that it will be applied only on the first row?

**Comment by MGaetan89** [comment]
You can find a couple of implementation by searching `SpacingItemDecoration` on Google.

**Comment by AndroidDeveloperLB** [comment]
@MGaetan89 There are multiple ones.
