### ISSUE TITLE
Xamarin Android Binding Library

### ISSUE THREAD

**Issue by btripp** [google/flexbox-layout#296]
Hey,

I created a Binding library for this to be used in Xamarin.Android. Not sure if you wanted to let your users know somehow.

https://www.nuget.org/packages/FlexboxLayoutXamarinBindingAndroid/

**Comment by thagikura** [comment]
Wow thanks! Let me comment it on the README!

**Comment by thagikura** [comment]
Added in [README](https://github.com/google/flexbox-layout/commit/811ff09f8487286a9ff0ec331767b175380a6dfc) is there is something you'd like to append, please let me know.
