### ISSUE TITLE
Use findFirstVisibleItemPosition in flexbox layout manager

### ISSUE THREAD

**Issue by Neha1490** [google/flexbox-layout#302]
How to use findFirstVisibleItemPosition , findLastVisibleItemPosition , findLastCompletelyVisibleItemPosition in flexbox layout manager?

**Comment by MGaetan89** [comment]
It's not yet included in the latest version including RecyclerView LayoutManager, but it will be in the next one (https://github.com/google/flexbox-layout/commit/928c553b4ec1302a88f5724e81fdfb35a8dde054).

**Comment by thagikura** [comment]
MGaetan89 is right. It's implemented in the dev_recyclerview branch, but hasn't been released yet.

I'm going to make a new release anytime soon.

**Comment by Neha1490** [comment]
Hi

Thanks for reply.
So what is alternative of findFirstVisibleItemPosition right now or how can I get if first item is visible(compleltely visible or partial visible both) ?

**Comment by MGaetan89** [comment]
If you update to version `0.3.0-alpha4` you can access those methods.

**Comment by Neha1490** [comment]
Thanks a lot.

**Comment by Neha1490** [comment]
Hi

What about  recyclerView.smoothScrollByOffset() ?
Is it supported yet or any alternative for it?
