### ISSUE TITLE
Item with flex_grow not visible

### ISSUE THREAD

**Issue by bashtian** [google/flexbox-layout#303]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce

Third item is not visible if first item is set to GONE

    <com.google.android.flexbox.FlexboxLayout
        android:id="@+id/flexbox_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:flexWrap="wrap"
        tools:showIn="@layout/activity_main">

        <TextView
            android:id="@+id/textview1"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="1"
            android:visibility="gone"
            app:layout_flexGrow="1.0"
            app:layout_wrapBefore="true"
            />

        <TextView
            android:id="@+id/textview2"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="2"
            app:layout_flexGrow="1.0"
            app:layout_wrapBefore="true"
            />

        <TextView
            android:id="@+id/textview3"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="3"
            app:layout_flexGrow="1.0"
            app:layout_wrapBefore="true"
            />

    </com.google.android.flexbox.FlexboxLayout>

## Expected behavior
Third item should be visible. Seems to be a similar problem as in https://github.com/google/flexbox-layout/issues/283

## Version of the flexbox library
https://github.com/google/flexbox-layout/commit/f93faf982f5b972c66e5b5bc711c0753c8172352

**Comment by thagikura** [comment]
Thanks! It's really a nice catch. Should be fixed by #304
