### ISSUE TITLE
Unable to achieve layout as shown in image

### ISSUE THREAD

**Issue by macymind** [google/flexbox-layout#308]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce

Create FlexboxLayout
Add 4 layouts with different size as shown in image.

## Expected behavior
It should look like
![exoected](https://user-images.githubusercontent.com/983011/27181585-cc710f96-51f5-11e7-8365-27574a01451f.png)

## Actual Result
I am receiving layout as shown
![actual result](https://user-images.githubusercontent.com/983011/27181687-45706cb6-51f6-11e7-9b6e-4e7a10c45282.png)

## Version of the flexbox library
0.3.0-alpha3

## Code

Flexbox Layout

    <com.google.android.flexbox.FlexboxLayout
        android:id="@+id/flx_category_list"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:flexWrap="wrap">

    </com.google.android.flexbox.FlexboxLayout>

Box image Layout

    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:clickable="true"
    android:focusable="true"
    android:foreground="?android:attr/selectableItemBackground"
    android:gravity="center">

    <ImageView
        xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/img_category"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:scaleType="centerCrop"
        android:layout_margin="1dp"
        android:contentDescription="Category Image"/>

    <TextView
        android:id="@+id/txt_category_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:padding="10dp"
        android:gravity="center"
        android:background="@android:color/white"
        android:textColor="@color/colorPrimary"
        android:textSize="20sp" />

    </RelativeLayout>

## Code to add box layout

     RelativeLayout layout = (RelativeLayout)mLayoutInflater.inflate(R.layout.cell_category_card, null);
     ImageView imageView = (ImageView)layout.findViewById(R.id.img_category);
     TextView txtCategory = (TextView) layout.findViewById(R.id.txt_category_title);
     txtCategory.setText(caegoryTitle);
     Glide.with(this)
            .load(imagePath)
            .into(imageView);
     flexboxLayout.addView(layout);
     FlexboxLayout.LayoutParams layoutParams = (FlexboxLayout.LayoutParams)layout.getLayoutParams();
     layoutParams.setWidth(width);
     layoutParams.setHeight(height);

This code repeat for 4 layouts
Width and height for 4 layouts as follows:
    1. Width: screen_width / 2, Height: screen_width
    2. Width: screen_width / 2, Height: screen_width / 2
    3. Width: screen_width / 2, Height: screen_width / 2
    4. Width: screen_width, Height: screen_width / 2

So can we achieve this kind of layout with flexbox layout?

**Comment by thagikura** [comment]
No it's not supported. If you'd like to achieve that layout, please consider using other layouts.
(Could be a workaround that you wrap 2 and 3 in a ViewGroup, but it's not as flexible as having all separated views)

**Comment by seth-gravy** [comment]
Similar to https://github.com/google/flexbox-layout/issues/535
