### ISSUE TITLE
Recyclerview scroll with Flexbox layout manager

### ISSUE THREAD

**Issue by Neha1490** [google/flexbox-layout#312]
Hi

Does recyclerview scrolling stops working with FlexBox layout manager?

I have also wrapped recyclerview inside scroll view with android:fillViewport="true" option also but recycler view scrolling is not working.

**Comment by thagikura** [comment]
It should work. Can you link your project or code?

**Comment by Neha1490** [comment]
// XML FILE

this is my recyclerview
 <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical"/>

// Recycler view with scroll view that i have tried-

<ScrollView
        android:id="@+id/scrollview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scrollbars="vertical"
        android:layout_above="@+id/rlBottom"
        android:layout_below="@+id/header_layout"
        android:fillViewport="true" >

        
    <android.support.v7.widget.RecyclerView
        android:id="@+id/recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
      
    </ScrollView>

// JAVA FILE
FlexboxLayoutManager layoutManager = new FlexboxLayoutManager();
										layoutManager.setFlexWrap(FlexWrap.WRAP);
										layoutManager.setFlexDirection(FlexDirection.ROW);
										layoutManager.setAlignItems(AlignItems.STRETCH);
										recyclerView.setLayoutManager(layoutManager);

**Comment by Neha1490** [comment]
Hi

Its been solved...it was some other issue.

Thank you.
