### ISSUE TITLE
Is it possible to shrink wrap?

### ISSUE THREAD

**Issue by wightwulf1944** [google/flexbox-layout#331]
Tested with FlexBoxLayoutManager with RecyclerView in my own project and the demo playground app.
Also researched about css behavior to see if this is normal behavior.

## Issues and steps to reproduce
1. Set layout manager flexwrap to wrap and use with Recyclerview as usual
```java
FlexboxLayoutManager layoutManager2 = new FlexboxLayoutManager(this);
layoutManager2.setFlexWrap(FlexWrap.WRAP);
```
2. Set the recyclerview items to have 0dp width and height and inflate within adapter as usual
```xml
<ImageView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="0dp"
    android:layout_height="0dp"
    android:layout_margin="4dp"/>
```
3. In the adapter's `onBindViewHolder`, set the width, height, minWidth, minHeight, flexGrow, and flexShrink
```java
FlexboxLayoutManager.LayoutParams flexboxLp = (FlexboxLayoutManager.LayoutParams) imageView.getLayoutParams();
flexboxLp.setMinHeight(0);
flexboxLp.setMinWidth(0);
flexboxLp.setFlexGrow(0.0f);
flexboxLp.setFlexShrink(1.0f);
flexboxLp.width = thumb_width;
flexboxLp.height = thumb_height;
```

## Expected behavior
Items in the row should shrink to accommodate 1 more item before wrapping to the next line
Items should not grow to accommodate remaining space

## Actual behavior
Empty space is left at the end of the row and the next item is wrapped to the next line

> ![screenshot_20170705-200444](https://user-images.githubusercontent.com/2737347/27863588-6738a7e2-61bd-11e7-8d18-24057e5b1c44.png)

## Version of the flexbox library
0.3.0

## Link to code
I'm currently experimenting with this in my personal project [Chesto](https://github.com/wightwulf1944/Chesto3) the latest commit being https://github.com/wightwulf1944/Chesto3/commit/cf766fd59aafbe2e8c59525f48a04adf2c067197. Please see MainActivity.java, MainAdapter.java, and main_recycler_item.xml

**Comment by thagikura** [comment]
It's an expected behavior. 

flexShrink works if flexWrap is set to `nowrap` because with flexWrap set to `wrap` (or `wrap_reverse`), the FlexboxLayoutManager is going to put the view to the next line instead of overflowing it's parent.

If you want to fill the remaining space in each line, please try setting a positive value (e.g. 1f) to each item's flexGrow attribute.

**Comment by yuriy-budiyev** [comment]
And what if (in a FlexboxLayout) a single elemrnt in a row is larger then available width? Overflow parent?
