### ISSUE TITLE
All items startsfrom new line

### ISSUE THREAD

**Issue by frakc** [google/flexbox-layout#335]
## Issues and steps to reproduce
I am extending FlexboxLayout. My layout is part of viewholder in recyclerview. Insideviewholder I am calling method to populate flexlayout programatically. After that I see that all my items are alinged vertically.
![device-2017-07-20-172009](https://user-images.githubusercontent.com/1126230/28422200-00521c7a-6d70-11e7-86e6-912813090f6a.png)
## Expected result
view_2 should be allined to right of view_1

## Version of the flexbox library
  compile 'com.google.android:flexbox:0.3.0'

## Link to code
```
public class FlowTags extends FlexboxLayout {

  public FlowTags(Context context) {
    super(context);
    init();
  }

  public FlowTags(Context context, AttributeSet attributeSet) {
    super(context, attributeSet);
    init();
  }

  public FlowTags(Context context, AttributeSet attributeSet, int defStyle) {
    super(context, attributeSet, defStyle);
    init();
  }

  void init() {
    setAlignItems(AlignItems.STRETCH);
    setAlignContent(AlignContent.STRETCH);
    setFlexWrap(FlexWrap.WRAP);
    setFlexDirection(FlexDirection.ROW);
  }

  public void setTags(ArtistsListGSON model) {
    removeAllViews();
    if (model.getCountry() != null) createTag(model.getCountry().getName());
    if (model.getGenres() != null) {
      for (ArtistsListGSON.GenresEntity g : model.getGenres()) {
        createTag(g.getName());
      }
    }
a
  }

  private void createTag(String s) {
    View v = LayoutInflater.from(getContext()).inflate(R.layout.listitem_tag, this, false);
    FlexboxLayout.LayoutParams lp = (FlexboxLayout.LayoutParams) v.getLayoutParams();
    lp.setOrder(-1);
    lp.setFlexGrow(2);
    v.setLayoutParams(lp);
    TextView t = (TextView) v.findViewById(R.id.text1);
    t.setText(s);
    addView(v);
  }
}
```java

tag xml

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="match_parent"
  android:layout_height="match_parent"
  android:orientation="vertical"
  android:paddingRight="8dip">

  <TextView
    android:id="@+id/text1"
    android:layout_width="wrap_content"
    android:layout_height="18dip"

    android:background="@drawable/shape_bg_tag"
    android:gravity="center"
    android:paddingLeft="12dip"
    android:paddingRight="12dip"
    android:layout_marginBottom="2dip"
    android:layout_marginTop="6dip"
    android:textColor="@color/white"
    android:textSize="10sp"
    tools:text="Heavy Metal" />
</LinearLayout>
```xml

ViewHolder

```
static class MyViewHolder extends RecyclerView.ViewHolder {
    @BindView(R.id.im_preview) RoundedCornersImageView imPreview;
    @BindView(R.id.tv_spotify) TextView tvSpotify;
    @BindView(R.id.im_spotify) ImageView imSpotify;
    @BindView(R.id.im_flag) ImageView imFlag;
    @BindView(R.id.tv_artist) TextView tvArtist;
    @BindView(R.id.tv_follower_count) TextView tvFollowerCount;
    @BindView(R.id.tv_follow) FollowArtistButton tvFollow;
    @BindView(R.id.holder_tags) FlowTags holderTags;
    ArtistsListGSON model;

    public MyViewHolder(View itemView) {
      super(itemView);
      ButterKnife.bind(this, itemView);
    }

    void bindView(ArtistsListGSON model, FragmentActivity activity, int width, int height) {
      this.model = model;
      holderTags.setTags(model);
         }

**Comment by thagikura** [comment]
Hi, 
Thanks for the report, but I'm still not sure the relationship between the image you pasted and the classes you mentioned.

Is the image itself FlowTag class you extended or the image represents a ViewHolder and the FlowTag part of the image?
If the question is latter, please provide the xml for the ViewHolder.

**Comment by frakc** [comment]
Hello I created test project with this issue https://github.com/frakc/flex_test
![workspace 1_022](https://user-images.githubusercontent.com/1126230/28499002-28177e44-6fb4-11e7-9a61-b1dbff60b35e.png)
In that project red box is listitem for recyclerview and green box is flex layout, where i expect items with blue backgrount to be alighend horisintaly

**Comment by thagikura** [comment]
Thanks.

It's not a bug with FlexboxLayout.
For the children of FlowTags, you are inflating the listitem_tag.xml. And the root element of that XML LinearLayout with `layout_width=match_parent`. So it takes the entire horizontal space.

You don't need a wrapping LinearLayout if you want to wrap the items in the FlowTags.

```xml
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="wrap_content"
  android:layout_height="match_parent"
  android:orientation="vertical">

  <TextView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/text1"
    android:layout_width="wrap_content"
    android:background="#0000FF"
    android:layout_height="wrap_content"
    android:layout_margin="8dip"
    android:textSize="14sp"
    android:textColor="#FFFFFF"
    android:padding="8dip" />
</LinearLayout>
```

**Comment by thagikura** [comment]
By the way if you use the LayoutInsepctor in AndroidStudio, it's pretty easy to inspect your layout hierarchy like this type of issue.

**Comment by frakc** [comment]
Thanks for pointing that, my bad I paid attention only to textview bounds
