### ISSUE TITLE
FlexboxItemDecoration draws wrong HorizontalDecorations

### ISSUE THREAD

**Issue by ly85206559** [google/flexbox-layout#345]
- [ ] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

In drawHorizontalDecorations method
Calculate the bounds of mDrawable,
In line 255 left = Math.max(left, parentLeft);
And line 231 parentLeft = parent.getLeft() - parent.getPaddingLeft();
The bounds is related with parent,so do not need to calculate parent.getLeft().

**Comment by thagikura** [comment]
The calculation needs to take care of the bound of the parent and the view itself.
So I think it's necessary.
