### ISSUE TITLE
':app:_debugAnnotationProcessor' after it has been resolved

### ISSUE THREAD

**Issue by venkat125** [google/flexbox-layout#347]
- [ ] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
*Error:Cannot change dependencies of configuration ':app:_debugAnnotationProcessor' after it has been resolved.*
The above error throws when i about to sync this **[ compile 'com.google.android:flexbox:0.3.0' ]** dependency in module level build.gradle file.

Any help is really worth it. Thanks a lot in advance.

## Expected behavior
*Please describe what you expected would happen.*

## Version of the flexbox library
*e.g. 0.2.6, 0.3.0-alpha3*

## Link to code
*Please link to the code we can use to reproduce this issue.*
*A complete project we can build/run is preferred, if you can't provide one, please show*
*us relevant code*

**Comment by venkat125** [comment]
missed to add @aar in compile 'com.google.android:flexbox:0.3.0**@aar**'

**Comment by thagikura** [comment]
Sounds like this has been resolved, thanks.
