### ISSUE TITLE
Flexboxlayout not show enough items with Array Items size = 5

### ISSUE THREAD

**Issue by toanshaolin** [google/flexbox-layout#348]
- [ ] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
*Please replace this with steps to reproduce your issue.*

## Expected behavior
*Please describe what you expected would happen.*

## Version of the flexbox library
*e.g. 0.2.6, 0.3.0-alpha3*

## Link to code
*Please link to the code we can use to reproduce this issue.*
*A complete project we can build/run is preferred, if you can't provide one, please show*
*us relevant code*

**Comment by toanshaolin** [comment]
I am using an array which has 5 elements inside, then assign this array to the Flexboxlayout, but the Flexbox layout can only show 4 elements, I am using Flexbox layout in the dialog

**Comment by thagikura** [comment]
Could you link to your XML or paste it in this issue?

**Comment by toanshaolin** [comment]
Here is my XML

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:zhy="http://schemas.android.com/apk/res-auto"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@drawable/bg_dialog_add_item"
    android:orientation="vertical"
    android:paddingLeft="@dimen/margin_60dp"
    android:paddingRight="@dimen/margin_60dp"
    android:paddingBottom="@dimen/margin_20dp"
    android:paddingTop="@dimen/margin_20dp">


    <TextView
        android:id="@+id/tv_title"
        fontPath="@string/font_medium"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:gravity="center"
        android:text="@string/add_a_new_attribute"
        android:textColor="@color/color_black1"
        android:textSize="@dimen/ts_20sp" />

    <TextView
        style="@style/TextTitleEdittext"
        android:layout_marginTop="@dimen/margin_30dp"
        android:text="@string/name" />

    <com.noq.androidmerchant.custom.MyEditText
        android:id="@+id/met_name"
        android:layout_width="@dimen/min_width_edit_text_dialog"
        android:layout_height="wrap_content"
        android:inputType="text"></com.noq.androidmerchant.custom.MyEditText>

    
    
    
    
    
    
    
    
    
    
    <com.google.android.flexbox.FlexboxLayout
        android:layout_width="match_parent"
        android:layout_marginTop="@dimen/margin_12dp"
        android:layout_height="wrap_content"
        android:id="@+id/flexboxlayout"
        app:flexWrap="wrap"
        app:alignItems="flex_start"
        app:showDivider="middle"
        app:dividerDrawable="@drawable/divider_flex_suggestion"
        app:alignContent="flex_start" >
    </com.google.android.flexbox.FlexboxLayout>

    <TextView
        android:id="@+id/tv_add"
        fontPath="@string/font_bold"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginBottom="@dimen/margin_20dp"
        android:layout_marginTop="@dimen/margin_30dp"
        android:background="@drawable/btn_gradient"
        android:foreground="?attr/selectableItemBackground"
        android:gravity="center"
        android:paddingBottom="@dimen/margin_12dp"
        android:paddingTop="@dimen/margin_12dp"
        android:text="@string/add"
        android:textAllCaps="true"
        android:textColor="@android:color/white"
        android:textSize="@dimen/ts_14sp" />
</LinearLayout>

**Comment by toanshaolin** [comment]
I add item by Array
ArrayList<String>  mArraySuggestions = new ArrayList<>();
        mArraySuggestions.add("Size");
        mArraySuggestions.add("Sauce");
        mArraySuggestions.add("Spicy");
        mArraySuggestions.add("Seen");
        mArraySuggestions.add("Shang");

**Comment by thagikura** [comment]
What is the parent of those Views?

**Comment by toanshaolin** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@drawable/bg_dialog_add_item"
    android:orientation="vertical">
[....]
</LinearLayout>

**Comment by thagikura** [comment]
Is  it possible to paste the relevant screenshot with `Show layout bounds` option enabled in the developer options?

**Comment by thagikura** [comment]
It looks like the height is constrained by the dialog, not by the FlexboxLayout.
What happens if you use the same FlexboxLayout configuration in a place other than the dialog?

**Comment by toanshaolin** [comment]
It works well in Activity Full screen, seem problem come from Dialog. Thanks thanks
