### ISSUE TITLE
Lower the minSdk to support broader devices

### ISSUE THREAD

**Issue by freemindhack** [google/flexbox-layout#35]
有人集成在 minsdk 10么？或者兼容包

**Comment by thagikura** [comment]
Are you asking does the library support minSdk 10?
If so, no it doesn't support API levels lower than 14.
More than 97% of devices are covered by minSdk 14, I think it's practical enough.

I'll close this for now, please re-open if that doesn't answer your question.

**Comment by codmajik** [comment]
3% of one billion is a lot of phones to throw away, and that is just phones that access playstore. if you are in emerging markets where most Android phones are either secondhand or old stock and/or custom rom support for minsdk 10+ is a must.

Hope you would reconsider.

Note: 
I was able to make it work by replacing getMeasuredWidthAndState, etc with ViewCompat version.

**Comment by thagikura** [comment]
Ok, fair enough.
Sent a pull request ( #45 ) to lower the minSdk to 9.

I hope it's included in the next release.

**Comment by thagikura** [comment]
Fixed by #45. I'll release a new version anytime soon.
