### ISSUE TITLE
FlexboxLayout uses newer api which causes crash on api < 17

### ISSUE THREAD

**Issue by andrey-shikhov** [google/flexbox-layout#351]
## Issues and steps to reproduce
use flexbox in any layout on api < 17(10-16)

## Expected behavior
flexbox works

## Version of the flexbox library
0.3.0

## Link to code
Workaround: extend flexbox and create methods:

    @Override
    public int getPaddingStart() {
        return getPaddingLeft();
    }

    @Override
    public int getPaddingEnd() {
        return getPaddingRight();
    }

Also needed to override layoutparams and add methods getMarginStart and getMarginEnd same way and do not forget to override generateLayoutParams

## How to fix
Replace newer api with conditionals or use backward compatible methods.

**Comment by thagikura** [comment]
Hi @andrey-shikhov 

Thanks for your report. I did quick test with the demo-playground app to add paddingStart(End)  with an emulator whose API level is 15, but couldn't reproduce the crash.

Do you have an example layout or code that can reproduce the crash?

Thanks

**Comment by thagikura** [comment]
Hi @andrey-shikhov, is it possible to share the relevant piece of code to reproduce this?
Thanks.

**Comment by thagikura** [comment]
Please reopen it if this issue still persists.
