### ISSUE TITLE
How do I get the number of items per row

### ISSUE THREAD

**Issue by leon2017** [google/flexbox-layout#352]
mLayoutManager = new FlexboxLayoutManager(this);
mLayoutManager.setFlexDirection(FlexDirection.ROW);
mLayoutManager.setJustifyContent(JustifyContent.FLEX_START);
mLayoutManager.setFlexWrap(FlexWrap.WRAP);

this adapter layout width is wrap_content,How do I get the number of items per row for recyclerview

**Comment by thagikura** [comment]
You can use `FlexboxLayoutManager#getFlexLines`.
Each FlexLine has the number of views contained in the line.

Please reopen it if it's not what you expect.
