### ISSUE TITLE
flexbox layout doesn't work as expected on API 16

### ISSUE THREAD

**Issue by passerbywhu** [google/flexbox-layout#353]
## Issues and steps to reproduce
1. Delcare a flexboxLayout in NestedScrollView
2. Add some TextView wrapped in LinearLayout in the flexboxLayout

## Expected behavior
The last TextView in one row is partially visible instead of being positioned at new line.

## Version of the flexbox library
com.google.android:flexbox:0.3.0

## Link to code
`List<String> data = new ArrayList<>();
        data.add("Simple Chinese");
        data.add("Steam");
        data.add("Odyssey");
        data.add("Windows");
        data.add("Android");

        LayoutInflater inflater = LayoutInflater.from(this);

        for (final String entity : data) {
            final View tag = inflater.inflate(R.layout.platform_item_pure_text, mFlexboxLayout, false);
            final CheckBox tagName = (CheckBox) tag.findViewById(R.id.platformName);
            tagName.setText(entity);
            params = (FlexboxLayout.LayoutParams) tag.getLayoutParams();
            params.bottomMargin = getResources().getDimensionPixelOffset(R.dimen.filterTagBottomMargin);
            params.leftMargin = params.bottomMargin;
            tag.setLayoutParams(params);
            mFlexboxLayout.addView(tag);
        }`

platform_item_pure_text.xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:gravity="center"
    >
    <CheckBox
        android:id="@+id/platformName"
        android:text="Windows Mobile"
        android:paddingLeft="19dp"
        android:paddingRight="19dp"
        android:layout_width="wrap_content"
        android:layout_height="31dp"
        android:background="#F2F2F2"
        android:textColor="#606060"
        android:textSize="13sp"
        android:gravity="center"
        android:button="@null"
        />
</LinearLayout>`

flexbox_activity.xml
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    >
    <android.support.v4.widget.NestedScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        >
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            >
            <com.google.android.flexbox.FlexboxLayout
                android:id="@+id/flexboxLayout"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:flexWrap="wrap"
                >
            </com.google.android.flexbox.FlexboxLayout>
            <View
                android:layout_width="match_parent"
                android:layout_height="500dp"
                />
        </LinearLayout>
    </android.support.v4.widget.NestedScrollView>
</LinearLayout>
`

**Comment by passerbywhu** [comment]
And Finally I am confirmed that the version of FlexboxLayout caused this problem.
When I run the project under 0.2.6, it's OK.  But when I run it under 0.3.0, it's not right.

**Comment by thagikura** [comment]
Thanks for the report. Confirmed the issue on my end. Let me fix this.

**Comment by Gericop** [comment]
When can we expect 0.3.1 to be released?

**Comment by thagikura** [comment]
I'd like to fix (or defer) #356, #357, #358 issues as well before releasing the new version. Hope it doesn't take long.
