### ISSUE TITLE
when there is only one row, the childview's height fills the flexboxlayout

### ISSUE THREAD

**Issue by mundane799699** [google/flexbox-layout#358]
## Issues and steps to reproduce
though I specify the childview's height in xml file, when when there is only one row, the childview's height fills the flexboxlayout. I wonder if it's a bug.
[layout_flexboxlayout.zip](https://github.com/google/flexbox-layout/files/1324511/layout_flexboxlayout.zip)

## Version of the flexbox library
0.3.0

**Comment by thagikura** [comment]
It's not a bug because you set alignItems for FlexboxLayout as `stretch`.
If you don't want FlexboxLayout to fill the height, please set the attribute other than `stretch`
