### ISSUE TITLE
FlexBoxLayout is unable to pull resources in xml

### ISSUE THREAD

**Issue by Naman-Goyal** [google/flexbox-layout#360]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

My layout.xml file does not pull softcoded resources like strings that are referred to in the xml document. All other layout types are able to pull those resources, and I am able to access them programatically. This error only occurs for me in runtime— going to the design tab in my xml file shows the strings extracted as I want.

I'm using flexbox 0.3.0

Here's a link to my app (the file called Lab1)
https://github.com/Naman-Goyal/SignupApp

The FlexBoxLayout is in the activity_main.xml file

**Comment by thagikura** [comment]
Hi, thanks for the report.

I'm still not sure what the issue is.
What does mean by "pull softcoded resources"? Does cause runtime exception? I tried your app, but crashed didn't happen.

**Comment by Naman-Goyal** [comment]
By softcoded I mean referring to the strings.xml resources

For example line 52 of the activity_main.xml page is 

`android:hint="@string/username_hint"`

This should cause the Item in question to refer to line 5 of the strings.xml page

`<string name="username_hint">Username</string>`

Setting the hint of the EditText to "Username". However, when the app is run, the EditText is empty instead.

**Comment by thagikura** [comment]
Sorry it's not completely related to FlexboxLayout. This seems because the size of the view isn't visible or other reasons. 
If you want to confirm that string resource is visible, please try a simple layout such as FlexboxLayout having a single TextView.
