### ISSUE TITLE
getLocationOnScreen not working properly for FlexboxLayout children

### ISSUE THREAD

**Issue by eli99999** [google/flexbox-layout#364]
- [ ] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
*Please replace this with steps to reproduce your issue.*
i'm extending  FlexboxLayout under this configuration:
**
      this.setFlexDirection(FlexDirection.ROW);
        this.setFlexWrap(FlexWrap.WRAP);
        this.setAlignContent(AlignContent.FLEX_START);
        this.setAlignContent(1);
        this.setLayoutParams(new LayoutParams(LayoutParams.WRAP_CONTENT,
                LayoutParams.WRAP_CONTENT));**

and i'm adding buttons as childern
when the children are clicked i'm using view.getLocationOnScreen(location);
to get their screen location- i'm getting the right y for all of them but the same x for each on of them
## Expected behavior
*Please describe what you expected would happen.*

i should get each view the exact location as described : 
https://developer.android.com/reference/android/view/View.html#getLocationOnScreen(int[])

## Version of the flexbox library
*e.g. 0.2.6, 0.3.0-alpha3*

com.google.android:flexbox:0.3.0

## Link to code
*Please link to the code we can use to reproduce this issue.*
*A complete project we can build/run is preferred, if you can't provide one, please show*
*us relevant code*

**Comment by thagikura** [comment]
I tested it locally with the playground-demo app and the result was expected (the x was retrieved for each View differently).
Is it possible share the runnable code or example project that I can debug?

**Comment by thagikura** [comment]
Please reopen this if this issue still persists. Thanks.
