### ISSUE TITLE
the image child is overflow

### ISSUE THREAD

**Issue by xinxin1314** [google/flexbox-layout#365]
I want the child equal distribution the layout, when children is imageView, and the image is larger, the child can not equal distribution:
<com.google.android.flexbox.FlexboxLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:flexDirection="column"
            app:flexWrap="wrap"
            app:dividerDrawable="@drawable/item_divider"
            app:showDivider="middle">

            <com.juejian.nothing.widget.RoundedImageView
                android:id="@+id/iv_item_attention_three_img_one"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:layout_flexGrow="1"
                app:corner_radius="4dp"
                android:background="@color/C8"/>

            <com.juejian.nothing.widget.RoundedImageView
                android:id="@+id/iv_item_attention_three_img_two"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:layout_flexGrow="1"
                app:corner_radius="4dp"
                app:layout_wrapBefore="true"
                android:background="@color/C8"/>

            <com.juejian.nothing.widget.RoundedImageView
                android:id="@+id/iv_item_attention_three_img_three"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                app:layout_flexGrow="1"
                app:corner_radius="4dp"
                app:layout_wrapBefore="true"
                android:background="@color/C8"/>

        </com.google.android.flexbox.FlexboxLayout>

**Comment by thagikura** [comment]
It's expected because you specify the layout_height as `wrap_content` (if you set flexDirection as `row`, the  layout_width matters in that case).
The original size of the image is honored when `wrap_content` is set. If you want to distribute the height to each image, you need to specify the fixed amount such as layout_height="1dp".
