### ISSUE TITLE
How to fetch coordinate of dynamic button before its getting added to FlexboxLayout

### ISSUE THREAD

**Issue by Feroz-Istar** [google/flexbox-layout#368]
I have created two flex layout inside a relative layout. One is at top and other one is at bottom.
I am adding dynamic button in the bottom flexlayout and set onclick listener for each button.  In this onclick, Starting a animation from bottom flexlayout button coordinates till the top flexlayout coordinates where the button is going to be added.  I am using a temporay variable called lastposition for tracing the position of the view to be added in top flexlayout. How will i get to know row is fill with content in top flexlayout since my last position logic screws up in case of row getting filled and animation goes off screen. 

Please see github repo https://github.com/akshayISTAR/TfyLanguage 
Activity name : FlexActivity
layout name : activity_flex

**Comment by thagikura** [comment]
Hi, let me make sure if I understand your issue correctly.

Do you want to know in which row a View is going to be added to the FlexboxLayout before it's actually added to FlexboxLayout?
If so, short answer is no. You can't know it beforehand.

Please reopen the issue if you think there is still an issue.
Thanks.

**Comment by Feroz-Istar** [comment]
yeah i want the position with respect to the screen before its actually get added
