### ISSUE TITLE
Incorrect FlexLauoutGap for RTL

### ISSUE THREAD

**Issue by HarelM** [google/flexbox-layout#370]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
FlexLayoutGap="10px" inside a [dir]="'rtl'" 
`margin-right="10px"` is added

## Expected behavior
`margin-left="10px"` should be used in this case

## Version of the flexbox library
2.0.0-beta.9

## Link to code
Where can I get an initial plunker?
```html
<div  [dir]="'rtl">
  <div fxLayout="row" fxLayoutGap="10px">
    <div fxFlex="70">
      the gap is before this instead of after
    </div>
    <div fxFlex>
       Should be a gap between this and the previous on
    </div>
  </div>
</div>

**Comment by thagikura** [comment]
Looks like you are talking about another library.
Closing.
