### ISSUE TITLE
 Why is there no "android: gravity" attribute? Like "TextView"

### ISSUE THREAD

**Issue by sortjiajun** [google/flexbox-layout#372]
We need this attribute to center the contents of the layout.
Thank you for my doubts

**Comment by thagikura** [comment]
Because it's not part of the flexbox specification and can be achieved by using other flexbox attributes.

**Comment by Cylix** [comment]
For people that end up on that issue looking for a way to get a gravity-like behavior:

`app:justifyContent="flex_start|flex_end|space_between"`.

Thanks for the great lib btw!
