### ISSUE TITLE
Possible to evenly distribute children over rows?

### ISSUE THREAD

**Issue by morris86** [google/flexbox-layout#375]
I'm struggling to figure out how I can achieve the following behaviour.  I have a flexbox which is dynamically filled with items.  For this example we'll say 4 children of equal size.

On one device, all 4 children fit horizontally on screen, so we get:
[ 1 ] [ 2 ] [ 3 ] [ 4 ]

On a separate device, only 3 children will fit horizontally, and the current behaviour I get is:
[ 1 ] [ 2 ] [ 3 ]
[ 4 ]

What I'd like to achieve in this situation is:
[ 1 ] [ 2 ]
[ 3 ] [ 4 ]

I know that the `layout_wrapBefore` attribute on child 3 will achieve it, but I'm looking to dynamically load this and have to calculate which child requires `layout_wrapBefore` and manually set the attribute.

Is there a way I can configure my FlexboxLayout to do this?

**Comment by thagikura** [comment]
Unfortunately it's not supported by the flexbox.
If you want to have a fixed number of items, you may want to use a grid.
