### ISSUE TITLE
need to support buildtool 3.0.0

### ISSUE THREAD

**Issue by jjhesk** [google/flexbox-layout#376]
is that possible to support the latest buildtool? i have got 

Error:(42, 20) error: cannot access FlexboxLayout
class file for com.google.android.flexbox.FlexboxLayout not found

that is due to using the buildtool 3.0.0

**Comment by MGaetan89** [comment]
I'm using Android Gradle Plugin 3.0 in my application, as well as flexbox-layout 0.3.1, and I don't have any issue.
Are you sure that you defined your dependency correctly?

**Comment by jjhesk** [comment]
currently im tryging extend from the main class like so
```java
public abstract class ToggleButtonGroup extends FlexboxLayout {

```

detailed in here: https://github.com/HKMOpen/ToggleButtonGroup/blob/usebaseflexboxlayout/togglebuttongroup/src/main/java/com/nex3z/togglebuttongroup/ToggleButtonGroup.java#L16


The issue is the I cannot access the class from FlexboxLayout

**Comment by jjhesk** [comment]
issues resolved. with the new gradle i have to use "api" instead of "implementation" from using the library.
