### ISSUE TITLE
grid layout

### ISSUE THREAD

**Issue by jjhesk** [google/flexbox-layout#377]
is that possible to have grid layout. giving column 2, column 4 ?

**Comment by thagikura** [comment]
Having a fixed column isn't supported. If you need it, I recommend using GridLayout.

**Comment by jjhesk** [comment]
there is a temp solution. make the items with base width percentage to 49% and it works like a charm. let me know if there is a better solution. @thagikura

**Comment by yhuiyang** [comment]
@jjhesk does your temp solution always have a fixed 2 columns grid? (That's my test result about your temp solution)

What I want to achieve is a grid layout with dynamic columns count, but column count can only be even number. (2 or 4 or 6 .... columns) Any thought to achieve this?

I know I can have layout_wrapBefore set on even elements, but it can still wrap at odd elements. I think what I want is forcing not wrap before odd elements, but there is no such attribute.
I also think put 2 elements in one horizontal linearlayout, and then put that linearlayout into flexboxlayout, but there is vertical alignment issue.
