### ISSUE TITLE
Manifest merger failed since 0.3.1

### ISSUE THREAD

**Issue by youxiachai** [google/flexbox-layout#382]
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(25.4.0) from [com.android.support:design:25.4.0] AndroidManifest.xml:28:13-35
  	is also present at [com.android.support:recyclerview-v7:26.0.0] AndroidManifest.xml:25:13-35 value=(26.0.0).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:26:9-28:38 to override.

I change 0.3.0 it work well

**Comment by thagikura** [comment]
It's not an issue. The support library version used in the flexbox library was changed to 26.0 since 0.3.1.
It's different from the support library version in your project.

Please add `'tools:replace="android:value"'` as suggested to avoid that.
