### ISSUE TITLE
Is it possible to move set of edittext to next line?

### ISSUE THREAD

**Issue by midds109** [google/flexbox-layout#386]
Hi,

I am dynamically adding edittext in the Flexboxlayout as shown in below image. Each edittext holds just 1 character of the word.The space between the boxes is also an editext but I have kept it invisible.I would like to know if we can move the entire set of edittext after the invisible edittext(space) to next line whenever required instead of just the single edittext.

![e6c85ccb-6eda-4eb1-b4ce-161106d1202f](https://user-images.githubusercontent.com/34164416/33487914-e71ecb80-d6d4-11e7-8072-2ccbd705b77e.jpg)

I tried adding the edditext in a word to a linearlayout and adding it to the Flexboxlayout.But this caused fatal exception 
				PID: 8344
                                                                           java.lang.ClassCastException: com.google.android.flexbox.FlexboxLayout$LayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams

Is there any possible workaround for this problem?

**Comment by thagikura** [comment]
There is a property called `layout_wrapBefore` if you set it to `true` you can force a view placed in a next line.
I think you can set that attribute to true for a view after each space edittext.
