### ISSUE TITLE
Undocumented minSdkVersion change

### ISSUE THREAD

**Issue by TWiStErRob** [google/flexbox-layout#390]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
Include the library in a project with `minSdkVersion < 14`. 

## Expected behavior
It compiles.

## Version of the flexbox library
*0.3.1*

## Link to code
https://github.com/google/flexbox-layout/pull/338 merged in [this commit](https://github.com/google/flexbox-layout/commit/717a7b4533487281739e06d88a5d8ac2eaeb399c) should be mentioned in the [release notes](https://github.com/google/flexbox-layout/releases/tag/0.3.1). I see you're not following semver, but it's a major change regardless, not a bugfix.

**Comment by thagikura** [comment]
Thanks for pointing this out. It makes sense. Updated the [release note](https://github.com/google/flexbox-layout/releases/tag/0.3.1).
