### ISSUE TITLE
Gradle warns of mixing support versions

### ISSUE THREAD

**Issue by newmanw** [google/flexbox-layout#395]
- [X] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
Create application with dependency on support library version 25.2.0

## Expected behavior
Not sure what to do here, android studio / gradle will complain if the versions of the support library do not match exactly.

## Version of the flexbox library
any, none of the tags/releases include support v25.2.0

**Comment by Seddiks** [comment]
The same happend to me!

**Comment by thagikura** [comment]
This should be fixed by https://github.com/google/flexbox-layout/pull/396

**Comment by thagikura** [comment]
Should be fixed by #396
