### ISSUE TITLE
Feedback flexbox-layout Problem

### ISSUE THREAD

**Issue by tcqq** [google/flexbox-layout#405]
Hello, thank you your library, Now I am using [FlexibleAdapter](https://github.com/davideas/FlexibleAdapter)library and（flexbox-layout  LayoutManager） created a list, but i find a problem, I tried it for a long time and checked the logs, and at the same time I [consulted with the author of the adapter library](https://github.com/davideas/FlexibleAdapter/issues/548). did not find any problems in the adapter finally, Because if I use the default LayoutManager: "SmoothScrollLinearLayoutManager", Will not appear the following questions, If use: "FlexibleFlexboxLayoutManager", there will be the following problems.

## Problem: 
Check the location of the red arrow in the screenshot.
![image](https://user-images.githubusercontent.com/10644057/36641745-11db9982-1a70-11e8-965c-3ebc8b7e671a.png)
![image](https://user-images.githubusercontent.com/10644057/36641749-1c72fcb4-1a70-11e8-98ac-cf2e89dd3156.png)
![image](https://user-images.githubusercontent.com/10644057/36641752-228d5c8e-1a70-11e8-93b0-f56b6949d513.png)

## Link: 
Simple Code: https://github.com/tcqq/SimpleAdapter

**Comment by thagikura** [comment]
Hi, I checked you code and found that you extends FlexboxLayoutManager, which also implements IFlexibleLayoutManager.
These classes are coming from different libraries. I'm not sure what the IFlexibleLayoutManager interface expects, so you need to make sure whether these two libraries really fit together.
(e.g. I'm not sure why you always return 1 for getSpanCount method. Which doesn't seem to work for FlexboxLayoutManager)

Regarding that, I don't find any issues on FlexboxLzayoutManager on this issue.
Please reopen another issue with more concrete example.

**Comment by tcqq** [comment]
-I'm not sure what the IFlexibleLayoutManager interface expects, so you need to make sure whether these two libraries really fit together.

[Described in the "FlexibleAdapter" wiki](https://github.com/davideas/FlexibleAdapter/wiki/5.x-%7C-Third-party-Layout-Managers): The IFlexibleLayoutManager interface will make any third party LayoutManager suitable for FlexibleAdapter
![image](https://user-images.githubusercontent.com/10644057/36658324-f69985f8-1b0a-11e8-900e-a03dfbc1f00f.png)

-e.g. I'm not sure why you always return 1 for getSpanCount method. Which doesn't seem to work for FlexboxLayoutManage

Am I wrong at this location? How should I modify it is correct?

-Regarding that, I don't find any issues on FlexboxLzayoutManager on this issue.

But why I use other layout manager, for example: `SmoothScrollLinearLayoutManager` there is no problem, if there is a problem using `FlexibleFlexboxLayoutManager`, I asked the author of the adapter, he said: It is not related to the adapter since this component manages the items not the layout
![image](https://user-images.githubusercontent.com/10644057/36660176-29dddbb0-1b12-11e8-8a35-5830641e19fa.png)
I do not know how to change it now, you more experienced than me, can you help me?, thanks.
