### ISSUE TITLE
Flexwrap not available

### ISSUE THREAD

**Issue by 97balakrishnan** [google/flexbox-layout#409]
I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate
## Issue
I am not able to use the flexwrap attribute.
## Issues and steps to reproduce
*I had a FlexBoxLayout object .I couldn't add the flexWrap attribute it shows attribute not available.*

## Expected behavior
*Able to add flexwrap*

## Version of the flexbox library
*e.g. 0.2.6*
Iam using android studio 3

**Comment by thagikura** [comment]
Hi, 
Could you share the issue in details?
Do you have an example project that can reproduce the issue?

Also 0.2.6 is the old version. I highly recommend switch to the latest version (as of now 0.3.2)

**Comment by thagikura** [comment]
Please reopen it with more details.
