### ISSUE TITLE
Request: update sdks, remove buildToolsVersion

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/flexbox-layout#410]
I think you can remove `buildToolsVersion` (including its usages), as it is automatically get chosen, and you can update various repositories versions:

    ext {
        minSdkVersion = 14
        targetSdkVersion = 27
        compileSdkVersion = 27
        //        buildToolsVersion = "27.0.2"
        androidGradlePluginVersion = "3.0.1"
        androidMavenGradlePluginVersion = "1.5"
        gradleBintrayPluginVersion = "1.6"
        kotlinVersion = "1.2.21"
        supportLibVersion = "27.1.0"
        espressoVersion = "3.0.0"
        testRunnerVersion = "1.0.0"
        junitVersion = "4.12"
      }

**Comment by thagikura** [comment]
Sounds reasonable, thanks.

**Comment by thagikura** [comment]
Fixed by #414

**Comment by AndroidDeveloperLB** [comment]
Thank you!
