### ISSUE TITLE
Question: is it possible to save space for a view for a specific line?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [google/flexbox-layout#411]
Suppose I have a dynamic layout/recyclerView, meaning it gets its views programmatically.

On the right side of the first line, I wish to put a view that will take space no matter what, and the views on the left will take space as usual, without overlapping it.

Think of it as a newspaper example: the view on the right is an image, while the rest is text paragraphs. 

Is such a thing possible using this library?

**Comment by thagikura** [comment]
If I understand your question correctly, do you expect a layout similar to CSS float?
If so, it's not supported by flexbox.

**Comment by AndroidDeveloperLB** [comment]
Didn't know what it is, but searching on Google, yes. That's what I was thinking about.
Can you please consider adding it?
The purpose of the library is to wrap views when not possible anymore to put them, so this can be another rule to add.

**Comment by AndroidDeveloperLB** [comment]
Well that's the purpose of what this is:
![image](https://user-images.githubusercontent.com/5357526/37447391-978eba9c-282a-11e8-86b8-28021ef633f2.png)

**Comment by AndroidDeveloperLB** [comment]
"available space" is a rule that can be extended. If there is no available space due to something else that takes it...

**Comment by thagikura** [comment]
float is a completely different specification from flexbox. So adding that rule to this library doesn't make sense.

I'd consider clipping a TextView if I'd do that.

**Comment by AndroidDeveloperLB** [comment]
Sorry but HTML and CSS are things that I've used ages ago.
By "clipping a TextView" you mean you consider adding this to the library?

**Comment by thagikura** [comment]
No, sorry I'm not adding the float feature to this library.

**Comment by AndroidDeveloperLB** [comment]
But do you understand the needs for such a thing?

**Comment by AndroidDeveloperLB** [comment]
Maybe you could add a way to put a view on specific place in the layout/RecyclerView, and let all the rest of the views not overlap it?
