### ISSUE TITLE
FlexboxItemDecoration has problem with ConstraintLayout

### ISSUE THREAD

**Issue by aotian16** [google/flexbox-layout#419]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
1. put `RecyclerView` and a `ImageView` into `ConstraintLayout`
2. `RecyclerView` rely on `ConstraintLayout` and `ImageView`
3. `RecyclerView` use `FlexboxLayoutManager` and `FlexboxItemDecoration`

Decoration is not correct

## Expected behavior
`RecyclerView` show on screen and correct.

## Version of the flexbox library
```Groovy
dependencies {
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.google.android:flexbox:0.3.2'
    implementation 'com.android.support:recyclerview-v7:27.1.0'
}
```

## Link to code
[demo](https://github.com/aotian16/DemoFlexboxItemDecoration)

**Comment by aotian16** [comment]
Not work in 1.0.0 too.

```
dependencies {
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.google.android:flexbox:1.0.0'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
}
```

**Comment by thagikura** [comment]
Thanks for reporting this.
Could you tell me more details how the decoration is not correct?

**Comment by aotian16** [comment]
![image](https://user-images.githubusercontent.com/1320395/40778243-2058aaa8-6503-11e8-8a0c-2280f4c38fe4.png)

It shows like this

**Comment by thagikura** [comment]
Ok, it looks like the same issue with #336.
I'm afraid the issue is still not fixed, please follow that issue at the moment.
