### ISSUE TITLE
Enhancement: Breaking point hint

### ISSUE THREAD

**Issue by HubKing** [google/flexbox-layout#421]
- [ v] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

Let's say that it contains something like this.

    [label][input field] [label][input field] [label][input field] [label][input field]

Depending on the screen width, this may be broken into multiple lines. But if a human manually did it he would never break it like this, which is what FlexLayout did for me:

    [label][input field] [label][input field] [label]
    [input field] [label][input field]

Or suppose in the following case

    [label][A1 field] [label][A2 field] [label][B1 field] [label][B2field] [label][B3field]

If A and B are logically different, a human would break it like this

    [label][A1 field] [label][A2 field] 
    [label][B1 field] [label][B2field] [label][B3field]

instead of this

    [label][A1 field] [label][A2 field] [label][B1 field]
    [label][B2field] [label][B3field]

I cannot come up with the best solution for this, but I need something is needed to enhance this behaviour. It may be impossible to specify all like-breaking situations, but probably in most cases, the line breaks will be one (I replaced a horizontal LinearLayout with a FlexLayout, because on some phones the last view was clipped out. If so, something like this can easily solve it.

    [label][input field] [label][input field] [BreakHint] [label][input field] [label][input field]
    [label][A1 field] [label][A2 field] [BreakHint] [label][B1 field] [label][B2field] [label][B3field]

**Comment by thagikura** [comment]
This be solved by using the layout_wrapBefore attribute?
Please reopen it if my understanding is not correct.
