### ISSUE TITLE
How to measure the FlexboxLayout's height?

### ISSUE THREAD

**Issue by Jibinghao** [google/flexbox-layout#432]
I use the **BottomSheetDialog**，I want to measure the FlexboxLayout's height before the dialog is showing;

fblTag.measure(View.MeasureSpec.UNSPECIFIED, View.MeasureSpec.UNSPECIFIED);
"fblTag.getMeasuredHeight()" is error;
"fblTag.getHeight()" is 0;

**Comment by thagikura** [comment]
It's not possible to get the height before it's displayed.
