### ISSUE TITLE
Crash on runtime

### ISSUE THREAD

**Issue by yuelvic** [google/flexbox-layout#443]
App crashes when adding FlexboxLayout.

java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/view/ViewCompat;
        at com.google.android.flexbox.FlexboxLayout.onLayout(FlexboxLayout.java:564)

**Comment by thagikura** [comment]
Which version of FlexboxLayout? Also what targetSdkVersion, compileSdkVersion and if you enable the [jetifier](https://developer.android.com/studio/preview/features/#androidx_migration)? 

It's great If you have an example project that I can reproduce the issue.

**Comment by thagikura** [comment]
Please reopen the issue, with the update above.

**Comment by NooruddinLakhani** [comment]
Getting same crashing issue .. what would i do to fix it?

**Comment by yuelvic** [comment]
As what @thagikura have said, enabling the [jetifier](https://stackoverflow.com/questions/51680671/what-is-jetifier) will solve the problem.
