### ISSUE TITLE
Request for AndroidX compatible beta release

### ISSUE THREAD

**Issue by ebraminio** [google/flexbox-layout#445]
Hey. We like to use Flexbox with AndroidX but the fact it is not released yet keeps up having a failing CI bot [1](https://travis-ci.org/ebraminio/DroidPersianCalendar/builds/403970379#L1756) (and interestingly we can build the app locally without issue). Can you give us a hand, possibly with a AndroidX compatible release? Full source code of what we have is [here](https://github.com/ebraminio/DroidPersianCalendar/pull/231), we would love your overall review also :)

**Comment by ebraminio** [comment]
Now I have a compile issue locally also due to incompatibility with beta01 just like our CI. I wish flexbox was a part of AndroidX it self.

**Comment by thagikura** [comment]
The current pull request for converting the project to AndroidX was merged to master.
I'll merge it to an alpha branch and release an alpha version on top of the alpha branch.

**Comment by ebraminio** [comment]
Great! Please make it compatible with the latest beta01 version of AndroidX before tagging. Thanks :)

**Comment by thagikura** [comment]
1.1.0-beta1 version of the library should be available by now with AndroidX support.
Please let me know if you find any issues.
