### ISSUE TITLE
40+ Method Not Found Warnings on Enabling Proguard

### ISSUE THREAD

**Issue by aswinmohanme** [google/flexbox-layout#451]
![screenshot from 2018-07-27 16-37-04](https://user-images.githubusercontent.com/20600674/43317657-55b81974-91bb-11e8-8e95-7065aec65f58.png)
I 'm using the current latest version of the library (1.0.0), with a new android project with Kotlin. When I enable the minification around 40+ warnings are shown and the project is not compiled.

Here's my dependency list
```
dependencies {
    // Custom Libraries
    implementation 'com.google.android:flexbox:1.0.0'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.anjlab.android.iab.v3:library:1.0.44'
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:28.0.0-alpha3'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

My Project progaurd-rules.pro is empty

**Comment by aswinmohanme** [comment]
I think it's related to the new version 28 of the support library

**Comment by JackyFen** [comment]
wert

**Comment by brianguertin** [comment]
Is there any workaround for this? I don't think it works with v27.1.1 of support library either. It doesn't seem like a support library issue.

**Comment by brianguertin** [comment]
This is still broken for me with flexbox 1.1.0 and androidx

**Comment by Lekky71** [comment]
You can add
` --keep com.google.android.flexbox.FlexboxLayoutManager { *; }`
to your progaurd file

**Comment by serhii-k** [comment]
To fix this issue, add an explicit dependency on RecyclerView in your build.gradle, even if you don't use any.
Like so:
implementation 'com.android.support:recyclerview-v7:28.0.0'
Or for AndroidX:
implementation 'androidx.recyclerview:recyclerview:1.0.0'
