### ISSUE TITLE
Avoid duplicate measurements for children

### ISSUE THREAD

**Issue by thagikura** [google/flexbox-layout#46]
In the onMeasure method, child.measure may be called more than once (e.g. Called first in the first loop to determine the number of flex lines, then called later to be expanded/shrank based on flexGrow/flexShrink attributes also maybe called to be stretched based on alignItems/alignSelf attributes).

This may cause performance issue especially the child is a nested ViewGroup.
It will be efficient to defer the child.measure as much as possible to reduce the number of measurements of the same child.

**Comment by jiasonwang** [comment]
Flexbox nested flexbox will cause performance degradation,too much measure

**Comment by aitorvs** [comment]
Do you have any updates on this issue?

**Comment by thagikura** [comment]
I think this can be now closed. #514 should remove the unnecessary measure calls.
