### ISSUE TITLE
How to use this with android.support.v7.recyclerview ? 

### ISSUE THREAD

**Issue by kkotkkio** [google/flexbox-layout#462]
I'm using com.android.support:recyclerview-v7:27.1.1 in all of ListView in My app.
And I needs a flexLayout so I try to use this library but I'm looking at below.

![2018-10-04 2 21 36](https://user-images.githubusercontent.com/23737489/46454433-104f4680-c7e1-11e8-8c5a-b6685e172062.png)

How to use this library(flexbox-layout) in support.v7.recyclerview?

Needs help.. 

Thanks.

## Version of the flexbox library
'com.google.android:flexbox:1.1.0'

**Comment by MGaetan89** [comment]
Version 1.1.0 and up are meant to be used with AndroidX dependencies.
If you use the Support Libraries, you should stay with version 1.0.0.

**Comment by kkotkkio** [comment]
@MGaetan89 Thank u! It's fixed.
