### ISSUE TITLE
FlexboxLayoutManager layouts children to weird position when nowrap & justifyContent=center

### ISSUE THREAD

**Issue by kubode** [google/flexbox-layout#469]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
Can reproduce this issue using Flexbox Playground.
- Check RecyclerView
- Flex Direction: Row
- Flex Wrap: Nowrap
- Justify Content: Center
- Add some item

## Expected behavior
The vertical position of the children should not be moved.

## Version of the flexbox library
1.1.0

## Link to code
Nothing.
Here are captures instead.

Settings|GIF
---|---
![screenshot_1542176087](https://user-images.githubusercontent.com/5885032/48463904-fada2d00-e820-11e8-82ab-ee0f38d15f76.png)|![untitled](https://user-images.githubusercontent.com/5885032/48463905-fada2d00-e820-11e8-8deb-0a0dc3b96a55.gif)

**Comment by thagikura** [comment]
Thanks for filing the issue. Confirmed it can be reproducible.

**Comment by thagikura** [comment]
Should be fixed by #470
