### ISSUE TITLE
FlexboxLayout invisible in ListView

### ISSUE THREAD

**Issue by a251115100** [google/flexbox-layout#47]

**Comment by thagikura** [comment]
Could you share the layout xml you are using (or code snippet if you set it from code)?

**Comment by thagikura** [comment]
Please re-open it with your layout XML and the code snippet.
Thanks.

**Comment by a251115100** [comment]
I have two childView  in FlexboxLayout ,if i set one View gone ,FlexboxLayout invisible

**Comment by a251115100** [comment]
<com.google.android.flexbox.FlexboxLayout
            android:id="@+id/lay_marks"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_toLeftOf="@id/tv_movie_score"
            app:flexDirection="row"
            app:justifyContent="flex_start"
            >

            <TextView
                android:id="@+id/tv_movie_name"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginRight="@dimen/dp4"
                android:singleLine="true"
                android:text="电影名称哈哈哈"
                android:textColor="@color/black"
                android:textSize="@dimen/tsize_title"
                app:layout_flexShrink="1"/>

            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:gravity="center"
                app:layout_flexShrink="0">

                <com.kokozu.widget.flat.FlatTextView
                    android:id="@+id/tv_mark_new"
                    style="@style/Widget.Flat.Mark.MovieNew"
                    android:layout_marginRight="@dimen/dp4"
                    android:singleLine="true"
                    />

                <com.kokozu.widget.flat.FlatTextView
                    android:id="@+id/tv_mark_3d"
                    style="@style/Widget.Flat.Mark.3DIMAX"
                    android:singleLine="true"
                    />
            </LinearLayout>


        </com.google.android.flexbox.FlexboxLayout>

**Comment by a251115100** [comment]
if (isNew) {
            holder.tvMarkNew.setVisibility(View.VISIBLE);
        } else {
            holder.tvMarkNew.setVisibility(View.GONE);
        }
        if (is3D || isIMAX) {
            StringBuilder imax3D = new StringBuilder();
            holder.tvMark3d.setVisibility(View.VISIBLE);
            if (isIMAX) {
                imax3D.append("IMAX");
            } else {
                imax3D.append("3D");
            }
            holder.tvMark3d.setText(imax3D.toString());
        } else {
            holder.tvMark3d.setVisibility(View.GONE);
        }

**Comment by a251115100** [comment]
i must use LinearLayout package TextView

**Comment by thagikura** [comment]
The top of your pasted layout xml is truncated. Could you paste the full layout xml?
I tried locally with the children views whose visibilities are gone and it worked fine.

Also please confirm the following.
- Please try showing your layout not within part of the ListView
- Before setting the visibility from the code, is the layout in question visible?

**Comment by a251115100** [comment]
public class MyAdapter extends BaseAdapter {

    private Context mContext;

    public MyAdapter(Context context) {
        mContext = context;
    }

    @Override
    public int getCount() {
        return 100;
    }

    @Override
    public Object getItem(int position) {
        return position;
    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        Holder holder;
        if (convertView == null) {
            convertView = LayoutInflater.from(mContext).inflate(R.layout.item, null);
            holder = new Holder();
            holder.tv = (TextView) convertView.findViewById(R.id.tv);
            convertView.setTag(holder);
        } else {
            holder = (Holder) convertView.getTag();
        }
        if (position / 2 == 0) {
            holder.tv.setVisibility(View.VISIBLE);
        } else {
            holder.tv.setVisibility(View.GONE);
        }
        return convertView;
    }

    private static class Holder {
        private TextView tv;
    }
}

**Comment by a251115100** [comment]
[itemxml.txt](https://github.com/google/flexbox-layout/files/285827/itemxml.txt)

**Comment by thagikura** [comment]
Thanks. How was the following?

> Please try showing your layout not within part of the ListView
> Before setting the visibility from the code, is the layout in question visible?

**Comment by a251115100** [comment]
public class MainActivity extends AppCompatActivity {

    private ListView lv;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        lv = (ListView) findViewById(R.id.lv);
        lv.setAdapter(new MyAdapter(this));
    }
}

**Comment by a251115100** [comment]
[Uploading acitivity.txt…]()

**Comment by thagikura** [comment]
Could you try the following in your environment and see if you still see the invisible FlexboxLayout?
I didn't ask you to upload the code for your Activity.

> Please try showing your layout not within part of the ListView
> Before setting the visibility from the code, is the layout in question visible?

**Comment by a251115100** [comment]
[Uploading app.zip…]()

**Comment by a251115100** [comment]
[app.zip](https://github.com/google/flexbox-layout/files/286198/app.zip)

**Comment by diantahoc** [comment]
This bug also occurs if I put  5 `TextView` controls inside the Flexbox layout and set the visibility to gone for 2 `TextViews`. If I set 1 `TextView` to gone, the flexbox remains visible. 

What I have noticed is that if the `TextView`s **don't** fit in the screen width, the Flexbox is visible.

The workaround was to put all the individual text views inside a linearlayout as @a251115100 have mentioned.

The bug can be reproduced with the following code:

```xml
 <com.google.android.flexbox.FlexboxLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:flexDirection="row"
                app:flexWrap="wrap"
                app:justifyContent="center">


                    <TextView
                        android:id="@+id/text_view_correct_label"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_margin="5dp"
                        android:drawableLeft="@drawable/correct_pie_chart_icon"
                        android:drawablePadding="5dp"
                        android:text="@string/label_correct"
                        android:textColor="@color/color_text"
                        android:textSize="@dimen/generic_text_size" />

                    <TextView
                        android:id="@+id/text_view_skipped_label"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_margin="5dp"
                        android:drawableLeft="@drawable/skipped_pie_chart_icon"
                        android:drawablePadding="5dp"
                        android:text="@string/label_skipped"
                        android:textColor="@color/color_text"
                        android:textSize="@dimen/generic_text_size" />

                    <TextView
                        android:id="@+id/text_view_assisted_label"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_gravity="center"
                        android:layout_margin="5dp"
                        android:drawableLeft="@drawable/assisted_pie_chart_icon"
                        android:drawablePadding="5dp"
                        android:text="@string/label_assisted"
                        android:textColor="@color/color_text"
                        android:textSize="@dimen/generic_text_size" />

                    <TextView
                        android:id="@+id/text_view_incorrect_label"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_margin="5dp"
                        android:drawableLeft="@drawable/incorrect_pic_chart_icon"
                        android:drawablePadding="5dp"
                        android:text="@string/label_incorrect"
                        android:textColor="@color/color_text"
                        android:textSize="@dimen/generic_text_size" />

                    <TextView
                        android:id="@+id/text_view_reported_label"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_margin="5dp"
                        android:drawableLeft="@drawable/reported_pie_chart_icon"
                        android:drawablePadding="5dp"
                        android:text="@string/label_reported"
                        android:textColor="@color/color_text"
                        android:textSize="@dimen/generic_text_size" />

            </com.google.android.flexbox.FlexboxLayout>
```

**Comment by thagikura** [comment]
Thanks for the clarification. I'll take a look.
