### ISSUE TITLE
Attach Flexbox Manager on RecyclerView

### ISSUE THREAD

**Issue by Anargyres** [google/flexbox-layout#471]
- [ ] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

_This a duplicate issue but the existing issue is closed while the problem still exist_

## Issues and steps to reproduce
Try to set on Flexbox Manager on a RecyclerView
Android Studio say it's impossible

FlexboxLayoutManager extends android.support.v7.widget.RecyclerView.LayoutManager and not androidx.recyclerview.widget.RecyclerView.LayoutManager.

## Expected behavior
Recycler accept this manger and can use it 

## Version of the flexbox library
1.1.0

**Comment by thagikura** [comment]
A written in the README, since 1.1.0, flexbox-layout library expects androidx package. Please migrate to androidx. https://developer.android.com/jetpack/androidx/migrate
