### ISSUE TITLE
WhatsApp messenger like view

### ISSUE THREAD

**Issue by arsalankhan994** [google/flexbox-layout#472]
## Issues and steps to reproduce
I want to create message view like whatsapp using flexbox-layout. I have created 2 textview inside flexbox layout that is message and time. On first line everything goes fine. But when text message move to second line, than time automatically goes to third line. But in whatsapp messenger both message and time are on same line. Is there any way to restrict message text to not occupy full line.
 
![screenshot_20181128-112808 2 1](https://user-images.githubusercontent.com/16983518/49134876-ead54980-f306-11e8-9005-b28973357452.png)

## Version of the flexbox library
1.0.0

**Comment by thagikura** [comment]
Hi, please debug this with the layout inspector on Android Studio and check the attributes assigned to each TextView.
Let me close this since this seems to be not an issue.
