### ISSUE TITLE
ee

### ISSUE THREAD

**Issue by dhna** [google/flexbox-layout#492]
- [ ] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
*Please replace this with steps to reproduce your issue.*

## Expected behavior
*Please describe what you expected would happen.*

## Version of the flexbox library
*e.g. 0.2.6, 0.3.0-alpha3*

## Link to code
*Please link to the code we can use to reproduce this issue.*
*A complete project we can build/run is preferred, if you can't provide one, please show*
*us relevant code*

**Comment by MGaetan89** [comment]
This doesn't look like an actual issue. Can you close it?
