### ISSUE TITLE
onCreateViewHolder    all the time 

### ISSUE THREAD

**Issue by woleigeququ** [google/flexbox-layout#497]
adapter = new FragHomeAdapter(mFragmentContext);
        FlexboxLayoutManager layoutManager = new FlexboxLayoutManager(mFragmentContext);
        layoutManager.setFlexDirection(FlexDirection.ROW);
        layoutManager.setFlexWrap(FlexWrap.WRAP);
        layoutManager.setAlignItems(AlignItems.STRETCH);

        fh_rv.setLayoutManager(layoutManager);
        fh_rv.setAdapter(adapter);
-----------------------
FragHomeAdapter :
if(viewType==BANNER){
            vh = new BannerAdVH(mInflater.inflate(R.layout.ff_normal_item_banner, parent,false));
        }else if(viewType==NEWS){
            vh = new NewsVH(mInflater.inflate(R.layout.fh_item_news, parent,false));
        }

    private class NewsVH extends RecyclerView.ViewHolder {
        private ImageView newsImg;
        public NewsVH(View view) {
            super(view);
            newsImg = view.findViewById(R.id.fh_item_news_img);
        }
        public void setData(final int realPosition){
            Log.e("temp"," :"+  1111); // invoked all the time
            ViewGroup.LayoutParams lp = newsImg.getLayoutParams();
            if (lp instanceof FlexboxLayoutManager.LayoutParams) {
                FlexboxLayoutManager.LayoutParams flexboxLp = (FlexboxLayoutManager.LayoutParams) lp;
                flexboxLp.setFlexGrow(1.0f);
                if(realPosition%3==0){
                    flexboxLp.setFlexGrow(3.0f);
                }
                flexboxLp.setAlignSelf(AlignSelf.FLEX_END);
            }
            ...
                Glide.with(mContext).load(url).apply(options).into(newsImg);
          ...
    }
------------------------
now the problem is   when banner autoplay , method onCreateViewHolder onBindViewHolder  will be invoked , I dont know why...    I use LinearLayoutManager instead will not invoked            thank you

**Comment by LuigiPapinoDrop** [comment]
I have the same issue.
Did you find a solution?

**Comment by woleigeququ** [comment]
sorry， it's been a long time , and I prolly didn't find a solution

**Comment by huigeee** [comment]
RecyclerView本身有复用机制，缓存池缓存的数量有限，而你的一页显示的内容超过了这个缓存池，RecyclerView必然会每次都创建，由于缓存池不够大，后面创建的view不会缓存，造成你看到的现象并且有内存泄漏的风险。

手动改改recyclerview的缓存池的size就好了
