### ISSUE TITLE
Publish artifact on maven.google.com

### ISSUE THREAD

**Issue by julioromano** [google/flexbox-layout#505]
- [X] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
The flexbox artifact can only be found on jcenter.

```
FAILURE: Build failed with an exception.

* What went wrong:
Gradle yields the following error if `jcenter()` is not in the `repositories {}` configuration closure.

Could not determine the dependencies of task ':app:testDebugUnitTest'.
> Could not resolve all task dependencies for configuration ':widgets:debugUnitTestRuntimeClasspath'.
   > Could not find com.google.android:flexbox:1.1.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/google/android/flexbox/1.1.0/flexbox-1.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/google/android/flexbox/1.1.0/flexbox-1.1.0.jar
```

## Expected behavior
The following gradle repositories configuration should be enough to download the flexbox artifact.
```
allprojects {
    repositories {
        google()
    }
}
```

## Version of the flexbox library
any version

Please consider this to avoid future problems similar to https://issuetracker.google.com/issues/120759347#comment30

**Comment by omaksymov** [comment]
Seems it will be resolved in scope of https://github.com/google/flexbox-layout/issues/566 (which is duplicate, but apparently got more attention 🤷‍♂️)

**Comment by julioromano** [comment]
Duplicate of #566
