### ISSUE TITLE
AppWidget support - Problem loading Widget 

### ISSUE THREAD

**Issue by KLT1003** [google/flexbox-layout#558]
- [x] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
I tried to build an AppWidget according to https://developer.android.com/guide/topics/appwidgets with a FlexBoxLayout as the widgets main layout. Just put some simple Textview with fixed width/height (e.g. 80dp) as inner elements for testing purposes. As soon as I try to create the widget I get the appropriate calls (onReceive, onEnabled, onUpdate, etc.) but the Widget shows "Problem loading widget".
Logcat does not show any details to the cause (normally I would expect some layout inflating issues in the logcat).
**Does flexbox-layout support AppWidgets?**

## Expected behavior
Flexbox layout should work within an AppWidget.

## Version of the flexbox library
2.0.1

**Comment by dutscher** [comment]
+1

**Comment by thagikura** [comment]
No it's not supported at this moment.

As far as I concern, it's not supported to use layouts or views from non-Android framework libraries at this moment.

**Comment by KLT1003** [comment]
Unfortunate and also understandable that it's not a priority, but for clarification the widgets are native Android features and not a non-Android framework library.
