### ISSUE TITLE
Whats minimum sdk level required for FlexboxLayout ?

### ISSUE THREAD

**Issue by poojalad1424** [google/flexbox-layout#560]
- [ ] I have searched [existing issues](https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
*Please replace this with steps to reproduce your issue.*

## Expected behavior
*Please describe what you expected would happen.*

## Version of the flexbox library
*e.g. 0.2.6, 0.3.0-alpha3*

## Link to code
*Please link to the code we can use to reproduce this issue.*
*A complete project we can build/run is preferred, if you can't provide one, please show*
*us relevant code*

**Comment by LetrixZ** [comment]
```minSdkVersion = 14``` in build.gradle project file
