### ISSUE TITLE
mavenCentral() & version 3.0.0 error Could not GET 'http://tokbox.bintray.com/maven/com/google/android/flexbox/1.0.0/flexbox-1.0.0.pom'

### ISSUE THREAD

**Issue by ashrafamin91** [google/flexbox-layout#584]
- [x] I have searched this issues at (https://github.com/google/flexbox-layout/issues) and confirmed this is not a duplicate

## Issues and steps to reproduce
1) Disable jcenter() and used mavenCentral()
2) Then update to latest flexbox that support mavenCentral()
3) Sync Gradle
4) Rebuild Project
5) Build: failed Could not GET 'http://tokbox.bintray.com/maven/com/google/android/flexbox/1.0.0/flexbox-1.0.0.pom'

## Expected behavior
Rebuild project without error

## Version of the flexbox library
com.google.android.flexbox:flexbox:3.0.0

## Link to code
#1
...
//        jcenter() 
        mavenCentral()
...
#2
...
//    implementation 'com.google.android:flexbox:1.1.0'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'
...

**Comment by thagikura** [comment]
The library is now hosted on google maven. Please try with the google maven repository.
