### ISSUE TITLE
How can i use this library in jetpack compose

### ISSUE THREAD

**Issue by KishanViramgama** [google/flexbox-layout#616]
How can i use this library in jetpack compose. can i have implement in LazyRow

## Version of the flexbox library
*e.g. 0.2.6, 0.3.0-alpha3*

**Comment by uchennafokoye** [comment]
Hi Kishan, please consider using FlowRow and FlowColumn in Compose which has a similar functionality as FlexBox in Compose.

**Comment by KishanViramgama** [comment]
@uchennafokoye thank you for response i will check this
