### ISSUE TITLE
Empty Vertical Space when FlexBasisPercent is used in row based Flex

### ISSUE THREAD

**Issue by wallestery** [google/flexbox-layout#66]
Flexed items that are shrunk to fit 50% of the parent are leaving a considerable vertical gap equivalent to the size of the items before shrinking.

The flexbox layout attributes:

`        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:flexWrap="wrap_reverse"
        app:alignItems="stretch"
        app:alignContent="flex_start"
        app:flexDirection="row"
        android:id="@+id/flexbox"`

The imageviews attribute:

`lp.flexBasisPercent = 0.49f;`

Reproduced result:

![image](https://cloud.githubusercontent.com/assets/8191343/15799271/fcbddc0a-2a56-11e6-9843-791144235241.png)

**Comment by thagikura** [comment]
Hi,

Thank you for your report.

What are the children views and its intrinsic heights?
The flexBasisPercent only works for the main direction, if the `flexDirection=row` the attribute should affect only for the width of children.

**Comment by wallestery** [comment]
Hello,

It's all my pleasure! The children views are imageViews that load (400X300)px PNG files.
Kindly find the Java class code:

```
  ImageView myImage;
  FlexboxLayout.LayoutParams lp;

for(int i = 0; i < 20; i++){
            myImage = new  ImageView(this);
            myImage.setImageResource(R.drawable.accounting);
            lp  = (FlexboxLayout.LayoutParams) myImage.getLayoutParams();
            lp.flexBasisPercent = 0.49f;
            myImage.setLayoutParams(lp);
            flexbox.addView(myImage);
}
```

**Comment by thagikura** [comment]
Thanks for the clarification.

What happens if you set the adjustViewBounds for ImageViews to true?
https://developer.android.com/reference/android/widget/ImageView.html#attr_android:adjustViewBounds

**Comment by thagikura** [comment]
I believe this is not the issue for the FlexboxLayout.

Please reopen it if the problem persists.
