### ISSUE TITLE
how can I set a row space from a row to other row? it can move item next line automatically, I don't which item should to set marginTop

### ISSUE THREAD

**Issue by caoguodong** [google/flexbox-layout#71]

**Comment by thagikura** [comment]
Hi,

There are two ways to set a space between rows. (I'm assuming you set the `flexDirection` as `row`)
* Set marginTop (or marginBottom) for all children, if you want to set a fixed space.
* Set the `alignContent` property to either of `space_between` or `space_around` if you want to set spaces relative to the rest of the remaining vertical space.

This repository has a demo app as the `app` module you can try different parameters in the demo app.
by `./gradlew installDebug`

**Comment by caoguodong** [comment]
thank you, if have a attribute to set it , it be better
