### ISSUE TITLE
Failed to resolve: com.google.android:flexbox:0.2.1

### ISSUE THREAD

**Issue by merhawifissehaye** [google/flexbox-layout#77]
I added _compile 'com.google.android:flexbox:0.2.1'_  to my build.gradle (app) file and I got the above error. The automatic install takes a while, so how can I manually download and install the dependencies on OsX

**Comment by thagikura** [comment]
Hi,

The library is hosted on jcenter at this moment.
If you don't have the jcenter repository dependency, please retry it after you add the following dependency to your top `build.gradle` file.
(It doesn't matter if you use Mac, Linux or Windows)
```
allprojects {
    repositories {
        jcenter()
    }
}
```

Or you can manually download the flexbox-0.2.1.aar from [bintray](https://bintray.com/google/flexbox-layout/flexbox/0.2.1/view#files/com/google/android/flexbox/0.2.1) directly.

**Comment by thagikura** [comment]
Or I noticed the dependency in the issue title `com.google.android.android:flexbox:0.2.1` is wrong.
please make sure you add as `com.google.android:flexbox:0.2.1`
(Remove the duplicate ".android")

**Comment by merhawifissehaye** [comment]
@thagikura What do I do with the .aar file. Where do I put it? [And if you can, please explain what is the .aar file and what it adds to the sdk]

**Comment by thagikura** [comment]
Sorry it's out of the scope of this project. There are lots of information about the aar file format and how to import it in the existing project in the internet. (like this [one](http://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst))

Please refer to other external sites.

**Comment by thagikura** [comment]
Closing this. As I commented first, it's easier to download the library from jcenter than manually downloading the aar file.
Please reopne if you still have an issue in downloading the library from jcenter.

**Comment by merhawifissehaye** [comment]
I had to put `@aar` at the end of the dependency as follows
```
dependencies {
    compile 'com.google.android:flexbox:0.2.1@aar'
}
```
and sync gradle project before gradle could finish without errors. Thank you
