### ISSUE TITLE
[Wiki] Performance comparison with other existing layouts 

### ISSUE THREAD

**Issue by thagikura** [google/flexbox-layout#84]
It would be nice if performance comparison with existing layouts (LinearLayout or GridLayout) is explained.

FlexboxLayout is intended to offer flexible layout functionalities rather than performance improvement, but in some situations (like building a grid like layout with dynamic number of children), FlexboxLayout should reduce the nested ViewGroups.
It's useful to explain performance comparison in such cases, if it turns out FlexboxLayout has disadvantages compared to existing layouts, it will be also beneficial for recogniznig the room for optimization for FlexboxLayout.

**Comment by crossle** [comment]
What's result FlexboxLayout vs ConstraintLayout

**Comment by thagikura** [comment]
Closing. This is obsolete.
