### ISSUE TITLE
[Wiki] Another use case where FlexboxLayout is useful than other existing layouts

### ISSUE THREAD

**Issue by thagikura** [google/flexbox-layout#85]
Such as the #59 would be a nice example that demonstrates usefulness of the FlexboxLayout, otherwise it would be tricky if building it with existing layouts.

**Comment by lii2** [comment]
It might be better to put #59 onto a different page, that way people don't have to load the Fluid Grid use case every time they want to look at the replacement use case, it would also be easier to maintain the page.

**Comment by thagikura** [comment]
> Also: Can you please give me a link to the demo app you reference in #59
Oh the demo app is in this repo :)

You can install it by "./gradlew installDebug"

**Comment by lii2** [comment]
@thagikura I am still trying to think of a good example that uses layout_wrapBefore, but I cleaned up the grammar on Target Use Cases. Could you please look at it and tell me what if I missed anything.

https://github.com/lii2/flexbox-wiki/blob/master/Target-use-cases.md

**Comment by thagikura** [comment]
@lii2 Wow, thank you! It looks much better. Thanks for also correcting my grammar mistakes 👍 

For the section about layout_wrapBefore, the section seems to overlap the README explaining the layout_wrapBefore attribute. So let me merge the page excluding the layout_wrapBefore section.

Thanks!

**Comment by lii2** [comment]
What API level is the demo written in?

**Comment by thagikura** [comment]
minSdkVersion is 9, targetSdkVersion is 23.

Could you try downloading the whole repository by "git clone git@github.com:google/flexbox-layout.git" and import the downloaded project? The style/FlexItem should be in the app module in this repo.

**Comment by lii2** [comment]
Do you mean File > New > Import Project?

**Comment by thagikura** [comment]
It may change based on the OS, but in Mac, "File -> Open", then select the downloaded project.

**Comment by lii2** [comment]
It's working now. By the way, do you have documentation on generating views in a flexbox programmatically? example:

`
for ( i = 0, i<5; i++){
flexbox.addview():
]`

**Comment by thagikura** [comment]
Yes, `FlexboxLayout#addView` should work.
If you need a code example, the demo app uses the addView method.
E.g. https://github.com/google/flexbox-layout/blob/master/app/src/main/java/com/google/android/apps/flexbox/MainActivity.java#L148

**Comment by lii2** [comment]
I wrote a function to create imageview in a flexbox container programmatically, with layout_flexBasisPercent set to 45%,  however, there is no function to set the layout_flexBasisPercent in imageview, is there another way to do so?

**Comment by thagikura** [comment]
Closing this in favor of the blog post
https://android-developers.googleblog.com/2017/02/build-flexible-layouts-with.html
