### ISSUE TITLE
how to get the count of the line in this view

### ISSUE THREAD

**Issue by maoaixianyu** [google/flexbox-layout#96]
i use this view. i want to get the count of line in this view. How can i do?
in this picture, it has 2 line of textview. how can i get the  number 2? 
![2](https://cloud.githubusercontent.com/assets/17868022/16945040/ffd1b928-4dd5-11e6-98c8-72cb07e21394.JPG)

**Comment by thagikura** [comment]
At this moment, the API to retrieve the line count of the FlexboxLayout.
But the requirement sounds reasonable to me. I'll keep this issue open and convert it as a feature request.

**Comment by maoaixianyu** [comment]
ok. thanks

**Comment by thagikura** [comment]
`FlexboxLayout#getFlexLines()` method was added in #102.

I'll release the updated version of the library anytime soon.

**Comment by ramseysaab** [comment]
I need to see to!
